### ISSUE TITLE
Modificações básicas

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#1]
Olá, juntei algumas dúvidas sobre algumas alterações simples que eu queria realizar! (Espero que ajude alguém também):
- Caso eu queria atualizar o HXPHP, apenas tenho que trocar a pasta /src/HXPHP/ ou atualizo pelo composer?
- Como alterar o framework CSS/JS? Somente alterar a pasta do bootstrap?
- Onde adicionar pastas? Por exemplo: um cadastro de fotos, onde colocaria ela?
- Se eu quiser trabalhar com Sass, onde ficariam os .sass? E extrairia para a pasta /public/css/?

Desde já agradeço e parabenizo pelo excelente trabalho!

**Comment by brunosantoshx** [comment]
Olá, como vai?

Seguem as respostas:

+ Isso depende do que a atualização contempla, ou seja, caso a nomenclatura de algum módulo/serviço/helper e etc seja alterada, isto também deve refletir nos arquivos da pasta `app/`. Mas, no geral, é só atualizar a pasta `src` e o processo, por enquanto, é manual;
+ Para isto é só enviar os arquivos do teu framework para a pasta `public` e alterar isto no `Header.phtml` e `Footer.phtml`;
+ O ideal seria `/public/uploads`;
+ Você pode criar uma pasta `/public/scss` e compilar para `/public/css`.

Espero ter te ajudado.
Forte abraço e sucesso sempre!
