### ISSUE TITLE
Classes PHP no padrão MVC

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#10]
Olá mais uma vez comunidade!

Tenho uma dúvida de estruturação do MVC: 
- Quando eu quiser utilizar classes em PHP para, por exemplo, edição de fotos (`WideImage`), detecção de dispositivos móveis (`Mobile-Detect`), entre outras, como seria o tratamento? Digo, estanciaria e manipularia o Objeto no `Controller` e mandaria pra `View`, ou vice-versa?
- Onde eu armazenaria os arquivos `.php` das classes, na pasta `vendor` do `Composer`, e utilizaria `Namespaces`?

Desde já, muito obrigado pela ajuda!

**Comment by alextelles** [comment]
Estou com o mesmo problema, independente da que digito depois de http://localhost/sistema/ eu estou recebendo a mensagem:


Not Found
The requested URL /hxphp/index.php was not found on this server.

**Comment by brunosantoshx** [comment]
Olá @alextelles, como vai?

Todas as dúvidas, referentes à série do canal, devem ser publicadas no respectivo repositório. Também já temos uma `issue`, que foi publicada neste repositório infelizmente, com a solução para seu problema:

https://github.com/brunosantoshx/hxphp/issues/8#issuecomment-161653877

Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Olá caro @carusogabriel.

Neste caso, antes de tudo, você precisa categorizar esta classe, sendo as opções: Módulo; Helper ou Serviço.

Após categorizar, é só criar no mesmo padrão e utilizar no controller através do método `load()`.

Tomando como base, os dois exemplos passados, classificaria o `WideImage` como módulo, pois, deverá ser composto por vários arquivos e terá diversas responsabilidades. Já o `MobileDetect`, sempre em camelcase :), classificaria como serviço, pois, tem apenas uma única responsabilidade.

**Comment by carusogabriel** [comment]
Perfeito @brunosantoshx 

Mas no caso do `MobileDetect`, criaria um `Model`, ou `Models` são apenas para Banco de Dados?

**Comment by brunosantoshx** [comment]
O `Model` é utilizado quando trabalhamos com dados, ou seja, com a regra do negócio. O `MobileDetect` tem uma única responsabilidade, isto é, reportar um booleano e, portanto, se categorizaria perfeitamente como serviço.

**Comment by carusogabriel** [comment]
E serviços são tratados nos `Controllers`, que tratam as `Views`?

**Comment by brunosantoshx** [comment]
Sim, você injeta os serviços nos Controllers e, a partir disto, poderá manipular a view.
