### ISSUE TITLE
Possível duplicação do acesso a super global $_COOKIE

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#101]
Olá @brunosantoshx 

Estava olhando os códigos do HXPHP, e percebi que existe um [método](https://github.com/brunosantoshx/hxphp/blob/master/src/HXPHP/System/Http/Request.php#L179) na classe `Request` que retorna os dados da super global `$_COOKIE`. A [classe Cookie](https://github.com/brunosantoshx/hxphp/blob/master/src/HXPHP/System/Storage/Cookie/Cookie.php) já não é responsável por isso? Porque, se for o caso, seria comodo a criação de um método para o acesso a super global `$_SESSION`, não?

Abraços!

**Comment by skay1994** [comment]
o metodo da classe ``Request`` é para você poder pegar algum dado que precisa da variavel global, ja a classe ``Cookie`` vai manipular os cookies como setar novos, limpar, verificar se existe, e também retornar o valor do indice solicitado

**Comment by brunosantoshx** [comment]
Olá @carusogabriel e @skay1994, tudo bem?

O objetivo é tornar o HXPHP compatível com a PSR-7. Para compreender melhor porque existe `cookie` e não `session` recomendo a leitura de: http://www.php-fig.org/psr/psr-7/.

A ideia inicial é usar o Relay (http://relayphp.com/) para cumprir este objetivo. 

Forte abraço e sucesso sempre!

**Comment by carusogabriel** [comment]
Olá @brunosantoshx 

Entendi o apontamento e estudarei sobre o assunto.

Abraços!
