### ISSUE TITLE
Verificação ambiente atual

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#110]
Olá @brunosantoshx, como vai?

Estava enfrentando sérios problemas com os Environments recentemente, e acredito ter encontrado o problema: o método `__construct` da classe `DefineEnvironmet` levava em consideração apenas os ambientes `development` e `production`. Escrevi um código que resolve este problema, porém, acredito ter ficado robusto e complicado para o framework (que não é o objetivo). Gostaria que desse uma olhada e comentasse possível melhorias antes de submetermos um PR.

Código do método `__construct` da classe `DefineEnvironmet`:

```php
public function __construct()
    {
        //Servidor atual
        $server_name = $_SERVER['SERVER_NAME'];

        //Carrega todos os arquivos da pasta Environments
        foreach (new \FilesystemIterator(__DIR__.'/Environments', \FilesystemIterator::SKIP_DOTS) as $environment) {
            //Recebe o nome de cada um sem a extensão .php
            $envName = $environment->getBasename('.php');

            //Atribuição do namespace
            $envClass = 'HXPHP\System\Configs\Environments\\'.$envName;

            //Verificação de segurança se a classe realmente existe
            if(class_exists($envClass)) {
                //Estanciamento da classe environment
                $env = new $envClass;

                //Verificação se ambiente atual é o do env estanciado
                if(in_array($server_name, $env->servers)){
                    //Separação camelCase de Environment{Foo}
                    $currentEnv = preg_split('/(?=[A-Z])/', $envName);

                    //Atribuição
                    $currentEnv = strtolower($currentEnv[2]);
                    $this->currentEnviroment = $currentEnv;

                    //Saída do loop de repetição para ganho de tempo na aplicação
                    break;
                }
                else
                    continue;
            }
        }

        return $this->currentEnviroment;
    }
```

**Comment by brunosantoshx** [comment]
Fala grande @carusogabriel, tudo bem?

Achei bem legal a melhoria neste recurso e não acho que vai adicionar complexidade nas rotinas do programador. O código é bastante sugestivo e fácil de interpretar.

Posso estar equivocado, mas, se não me engano, instanciar a classe em uma variável para depois iterar no foreach seria uma boa prática de performance. 

Outro apontamento é que o método construtor não retorna valores.

Fico no aguardo do PR.
Forte abraço e sucesso sempre!

**Comment by carusogabriel** [comment]
Perfeito @brunosantoshx , estarei fazendo esta atribuição de variável e submetendo o PR. 

Sobre o `return`, alguns métodos `__contruct()` ao longo do Framerwork possuem o `return`(Ex: classes `Model`, `App`, `Request`, a própria classe atualmente retorna `$this->currentEnviroment`). Seria necessário um PR "corrigindo" isso, ou alguns métodos construtores precisam retornar valores?

**Comment by brunosantoshx** [comment]
Sim, seria necessário, afinal, são códigos sem qualquer utilidade. Acabei cometendo este equívoco porque queria usar `chaining` e acabei esquecendo de consertar.

**Comment by carusogabriel** [comment]
Perfeito. Estarei percorrendo o código a procura de `return` em métodos `__construct()` e farei este PR, e farei outro sobre a verificação dos Environments
