### ISSUE TITLE
Problemas para usar DROPDOWN no Bootstrap

### ISSUE THREAD

**Issue by guilherme-camargo** [brunosantoshx/hxphp#113]
Quando uso o dropdown ele simplesmente não faz nada ele age como um link qualquer, mas quando eu uso em uma pagina html ou phtml do modo simples sem o framework ele funciona normalmente. Gostaria de saber se isso ocorre só comigo e também se existe algo semelhando para substituir.

http://getbootstrap.com/components/#dropdowns

**Comment by carusogabriel** [comment]
Olá @guilherme-camargo 

Por acaso não seria a <b>falta</b> do arquivo `.js` do Bootstrap? Tente carrega-lo na view, pode ser isso!

Abraços e aguardo seu feedback.

**Comment by guilherme-camargo** [comment]
@carusogabriel Infelizmente não funcionou peguei e chequei se estava carregado na view e estava, chequei minha pasta bower components que é onde está o bootstrap também estava OK, mas por via das duvidas eu decidi baixar de novo o HXPHP e substituir somente a pasta bower components, mas nem assim funcionou.

**Comment by skay1994** [comment]
veja se no console do navegador mostra algum erro
