### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by gilglecio** [brunosantoshx/hxphp#119]
$app->get('/', 'Controllers\IndexController@index');

**Comment by gilglecio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Routes](https://trello.com/c/MPp1xsr2/138-routes)

**Comment by gabriel-caruso** [comment]
Olá @gilglecio , como anda os desenvolvimento das rotas no HXPHP?

**Comment by giovanidomingues** [comment]
No meu sistema quando clico pra editar o perfil, da esse erro 

Fatal error: Uncaught Error: Class 'Form' not found in C:\xampp1\htdocs\creditrans\app\views\perfil\editar.phtml:12 Stack trace: #0 C:\xampp1\htdocs\creditrans\src\HXPHP\System\View.php(288): require_once() #1 C:\xampp1\htdocs\creditrans\src\HXPHP\System\App.php(112): HXPHP\System\View->flush() #2 C:\xampp1\htdocs\creditrans\index.php(36): HXPHP\System\App->run() #3 {main} thrown in C:\xampp1\htdocs\creditrans\app\views\perfil\editar.phtml on line 12

e esse Warning:

 Invalid argument supplied for foreach() in C:\xampp1\htdocs\creditrans\src\HXPHP\System\Http\Request.php on line 143

**Comment by gabriel-caruso** [comment]
@giovanidomingues Por favor, abra uma nova `issue` para relatar o seu problema!

PS: Leia o `Warning`, ele pode ser útil na correção de seu erro.

**Comment by giovanidomingues** [comment]
ja resolvi os dois
