### ISSUE TITLE
ocorre um erro no meu servidor linux compartilhada, seria alguma configuraçao de chmod?

### ISSUE THREAD

**Issue by William-de-Souza** [brunosantoshx/hxphp#122]
Pessoal comecei a implementar hxphp para criar o login e cadastro para um cliente o DEADLINE ja me enforcou a mais de tres semanas 
o que eu posso fazer 
tentei rodar o composer install via ssh tbm parece que rodou a principio

http://sistemahx.provisorio.ws/sistema/login/logar/ 

estou usando osistema logincom  hxphp q esta na pasta sistema como subpasta e nao como subdominio , me ajudem preciso pelo menos de uma direçao tenho interesse em aprender mais sobre o framework

Fatal error: Uncaught exception 'ActiveRecord\DatabaseException' with message 'exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sistemahx.login_attempts' doesn't exist' in /home/storage/a/fa/96/sistemahx1/public_html/sistema/vendor/php-activerecord/php-activerecord/lib/Connection.php:333 Stack trace: #0 /home/storage/a/fa/96/sistemahx1/public_html/sistema/vendor/php-activerecord/php-activerecord/lib/Connection.php(333): PDOStatement->execute(Array) #1 /home/storage/a/fa/96/sistemahx1/public_html/sistema/vendor/php-activerecord/php-activerecord/lib/adapters/MysqlAdapter.php(25): ActiveRecord\Connection->query('SHOW COLUMNS FR...') #2 /home/storage/a/fa/96/sistemahx1/public_html/sistema/vendor/php-activerecord/php-activerecord/lib/Connection.php(275): ActiveRecord\MysqlAdapter->query_column_info('`login_attempts...') #3 /home/storage/a/fa/96/sistemahx1/public_html/sistema/vendor/php-activerecord/php-activerecord/lib/Table.php(402): ActiveRecord\Connection->columns('`login_att in /home/storage/a/fa/96/sistemahx1/public_html/sistema/vendor/php-activerecord/php-activerecord/lib/Connection.php on line 336

**Comment by William-de-Souza** [comment]
![image](https://cloud.githubusercontent.com/assets/25403171/25305688/5f4c1ea2-2756-11e7-8a80-c6622817f35a.png)
 ate aqui normal

**Comment by brunosantoshx** [comment]
Olá @William-de-Souza, como vai?

`Base table or view not found: 1146 Table 'sistemahx.login_attempts' doesn't exist'`. A própria mensagem que você postou já lhe responde qual é o problema: a tabela `login_attempts` não existe.

É muito importante ler com calma as mensagens de erro porque estão cada vez mais sugestivas.

Forte abraço e sucesso sempre!

**Comment by William-de-Souza** [comment]
![image](https://cloud.githubusercontent.com/assets/25403171/25317530/d23d6524-2850-11e7-8620-7fb86e577933.png)
poxa bruno obrigado por me ajudar , mas nao seria esse o caso creio

**Comment by William-de-Souza** [comment]
preciso colocar esse sistema no ar e senti muita confiança no hxphp e em sua aulas , mas preciso de ajuda nao estou conseguindo debugar o erro

**Comment by brunosantoshx** [comment]
Amigo, veja novamente com calma o print. Está faltando um `t`.

**Comment by William-de-Souza** [comment]
pouts......obg ... vou corrigir  0.o
realmente me enganei , espero que com essa alteraçao td funcione perfeitamente...  mt obg mais uma vez ...ddeeesculpe meu excesso de ansiedade ja me fez menos mal...  muito obrigado pela atençao e tbm  desejo muita saude muito sucesso sempre e saiba que pelo pouco que vejo atraves do canal da pra sacar que vc eh um cara bacana e um excelente profissional....   eh isso que faz o mundo girar....  obrigado mais uma vez e maos a obra.
