### ISSUE TITLE
Array como valor de uma sessão.

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#123]
Olá!

Eu costumo passar o retorno de uma mensagem (utilizando o getByCode) através de uma session, para poder exibi-lá em outra página.

No entanto, eu percebi que nas novas versões do HXPHP, tanto a classe **_Storage_** quanto a sua interface **_StorageInterface_** obrigam que o segundo parâmetro da função **_set_** seja obrigatoriamente uma string, ou seja, não é possível passar um array para a sessão.

Isso não é ruim?

Obrigado e abraços!

**Comment by brunosantoshx** [comment]
Olá @Lesnock, boa tarde.

Boa observação! Já corrigi o problema e subi o commit.

Obrigado pela contribuição.
Abs
