### ISSUE TITLE
Post não funciona com campo array

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#125]
Olá @brunosantoshx , tudo bem?

Hoje tentei utilizar a flag `FILTER_FORCE_ARRAY` para receber um array através do método POST, mas obtive um erro de PHP.

Dei uma olhada no arquivo  `src\HXPHP\System\Http\Request.php`, e aparentemente todos os campos do POST estão passando pela função `trim`, o que é um problema, já que esta função não aceita um _array_ como argumento.

Há alguma maneira de fazer isso, ou é preciso corrigir o código do framework?

Obrigado e abraços!

**Comment by carusogabriel** [comment]
Acredito que seria necessário fazer uma verificação se está FLAG foi setada, ou (o que levaria um tempo maior de processamento) verificar se é um array e realizar um loop através dele. A função `trim` é necessário quando se trata de formulários, pois muitos usuários pressionam a tecla `space` para verem onde está o cursor, gerando espaços desnecessários.

**Comment by Lesnock** [comment]
Olá @carusogabriel , tudo bem?

Acredito que essa verificação seja necessária então.
Em relação ao loop, acho que um `array_map('trim', $array);` já resolveria os nossos problemas.

Obrigado!

**Comment by brunosantoshx** [comment]
Olá @Lesnock, boa noite. Tudo bem?

Realmente é necessário corrigir este bug e também pensei no uso do `array_map` desde que se trate de um array.

Vou providenciar o ajuste.

Obrigado pela notificação.
Forte abraço e sucesso sempre!

**Comment by FilippeMafra** [comment]
Boa noite, este problema foi corrigido?
