### ISSUE TITLE
LoginAttemp não registra no banco.

### ISSUE THREAD

**Issue by KievMaia** [brunosantoshx/hxphp#126]
Boa tarde Bruno,

Fiz refiz a aula 8 e as tentativas de login não estão sendo registradas no banco.
Modelei meu banco exatamente como você mostrou na aula 2, no entanto na aula 8 ao 21:13 min, você mostra a modelagem de outra maneira. Você poderia me mostrar como deve estar modelado o banco.

![image](https://cloud.githubusercontent.com/assets/9864866/25760555/b62c4c5e-31ad-11e7-9e2b-3db7c267e23a.png)
![image](https://cloud.githubusercontent.com/assets/9864866/25760578/cce6aa20-31ad-11e7-97f6-7dd3cb25a170.png)

Obrigado!

**Comment by KievMaia** [comment]
Olá,

refiz novamente a base de dados, e agora parece que está ok.
No entanto ao registrar as tentativas de login, algo está dando errado ao registrar a data e hora, poderia me ajudar a resolver este problema? já tentei de tudo.

![image](https://cloud.githubusercontent.com/assets/9864866/25762788/8b29683a-31b6-11e7-9667-338e97a19a5c.png)


Obrigado!

**Comment by carusogabriel** [comment]
Olá @kievmaia 

De uma lida mais atenta aos erros, eles dizem muita coisa por si só. Este, no caso, está com erro no formato da data. Pesquise pelos tipos de datas aceitas pelo MySQL, e como configurar esses tipos no PHPActiveRecord, você encontrará a solução!

Abraços

**Comment by brunosantoshx** [comment]
Olá @KievMaia, como vai?

Recomendo trocar o tipo `TIMESTAMP` para `DATETIME` nas colunas `created_at` e `updated_at` e acredito que o problema será resolvido.

Forte abraço e sucesso sempre!
