### ISSUE TITLE
Problema com barra no final da URL

### ISSUE THREAD

**Issue by felipeacelino** [brunosantoshx/hxphp#127]
Na ação de cadastrar usuário, quando a URL tem uma barra no final, desse modo:
http://localhost/hxphp/cadastro/

Ocorre um problema, além de não ser inserido o usuário e não ser retornado nenhum erro, a URL é alterada para:
http://localhost/hxphp/cadastro/cadastro/cadastrar/

E assim vai encadeando infinitaemnte....

Porém se a URL estiver sem barra no final:
http://localhost/hxphp/cadastro

Funciona normalmente...

**Comment by brunosantoshx** [comment]
Olá @felipeacelino, boa noite. Tudo bem?

Essa é a primeira vez que este tipo de problema é reportado, portanto, a primeira hipótese é algum problema na configuração do seu ambiente. Você consegue testar a sua aplicação em outro ambiente?
