### ISSUE TITLE
PSR-0

### ISSUE THREAD

**Issue by Dalmazox** [brunosantoshx/hxphp#128]
Olá Bruno, dei uma olhada no projeto e percebi que o autoload do composer ainda permanece sendo a PSR-0, no caso ela está depreciada. Não seria recomendado a atualização para a PSR-4?

**Comment by brunosantoshx** [comment]
Olá @Dalmazox, boa noite. Tudo bem?

Excelente observação! São os pequenos detalhes que fazem toda a diferença! Em seguida, já vou providenciar o merge do seu PR.

Obrigado pela contribuição.
Forte abraço e sucesso sempre!
