### ISSUE TITLE
Erro de formato de data ao inserir na tabela login_attempt

### ISSUE THREAD

**Issue by leobarreto** [brunosantoshx/hxphp#129]
Ola, Bruno.
Estou com o erro 

**Fatal error: Uncaught ActiveRecord\DatabaseException: PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2017-06-15 07:11:43 BRT' for column 'created_at' at row 1 in C:\wamp\www\rmreboque\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 337**

que sempre acontece quando tento me logar com a senha errada. Se coloco a coluna como VARCHAR vai de boa. Acho que é por causa deste BRT que está colocando no final.

A coluna created_at é TIMESTAMP

Grato desde já

**Comment by flemej** [comment]
Eu tive problemas com formato de datas e pra mim resolveu inserindo a linha abaixo no config.php

ActiveRecord\Connection::$datetime_format = 'Y-m-d H:i:s';

**Comment by flemej** [comment]
Se o seu código tem registro de Login inválido para bloqueio de acesso, deve ser na hora de gravar a hora da tentativa incorreta :)

**Comment by leobarreto** [comment]
resolvido com a dica do  **@flemej**.

Muito grato

**Comment by brunosantoshx** [comment]
Olá @flemej e @leobarreto, boa noite. Tudo bem com vocês?

Primeiramente, gostaria de agradecer ao @flemej que prontamente prestou o suporte ao companheiro. 

Só gostaria de confirmar com vocês: A versão do PHP que estão usando é a 7+ e o erro ocorre de imediato ao rodar o HXPHP?

Se for isto, vamos adicionar a solução do @flemej ao código do HXPHP. Inclusive, se quiser fazer o pull request, será muito bem vindo.

Forte abraço e sucesso sempre!

**Comment by leobarreto** [comment]
@brunosantoshx sim. estou utilizando a 7.0.10 e o erro somente ocorre na tentativa de login errada.

**Comment by brunosantoshx** [comment]
O @flemej subiu um PR com a solução que foi eficaz pra ele. Já fiz merge e agora é atualizar e testar.

Abração e sucesso sempre!
