### ISSUE TITLE
Registro de módulos nas configurações.

### ISSUE THREAD

**Issue by brunosantoshx** [brunosantoshx/hxphp#13]
Olá @carusogabriel, como vai?

Estava pensando na seguinte implementação:
Registrar os módulos, que serão utilizados na aplicação, no arquivo `app/config.php`. Atualmente, os módulos são passados no construtor do arquivo `System/Configs/RegisterModules.php`.

O que acha de trabalharmos nesta melhoria?

**Comment by carusogabriel** [comment]
Olá @brunosantoshx!

Perfeito, trabalharei em ideias e commitarei no meu [fork do HXPHP](https://github.com/carusogabriel/hxphp), e atualizo a issue para você analisar e aderir caso queria!
