### ISSUE TITLE
Dúvida da adição de classes no autoloader

### ISSUE THREAD

**Issue by JoaoSilvaC** [brunosantoshx/hxphp#132]
eu estou desenvolvendo meu TCC e estou usando o framework porém eu preciso gerar boleto e nota a maneira mais fácil é usar classes prontas só que não consigo eu até faço parte do composer mas na hora de incluir uma classe no autoloader eu não consigo sempre incluo no arquivo errado alguém por favor me ajuda estou precisando gerar isso rápido

**Comment by brunosantoshx** [comment]
Olá @JoaoSilvaC, boa noite. Tudo bem?

Que bacana! Depois pode me enviar mais detalhes? Meu e-mail é contato@hxphp.com.br. Pretendo adicionar os cases feitos com o HXPHP no site futuramente.

É exatamente este o caminho certo: autoload com Composer. Se você instalar a dependência (classe de boleto) via composer é automático! Só precisa se atentar para namespaces e não tem erro! 

Agora se você quer usar classes isoladas você pode usar o autoload via Classmap (Um vídeo pra te ajudar: https://www.youtube.com/watch?v=V2k2VSGEZWQ). É bem tranquilo da mesma forma.

A última forma é você adaptar e transformar esta classe em um módulo do HXPHP. Assim você poderá carregar e controlar com precisão na sua aplicação.

Espero ter ajudado.
Forte abraço e sucesso sempre!
