### ISSUE TITLE
Utilizar PHPActiveRecord no Services ou Tools

### ISSUE THREAD

**Issue by erickmourasilva** [brunosantoshx/hxphp#134]
Gostaria de saber como eu poderia fazer para realizar consultas no banco de dados diretamente de um serviço ou de um tools, pois o phpactiverecord só funciona nos controllers ou models.
Criei um serviço no Services, mas lá não reconhece nada adicionado pelo composer.

**Comment by brunosantoshx** [comment]
Olá @erickmourasilva, boa noite. Tudo bem?

O ideal é você passar os valores do seu banco de dados para o serviço através do controller, isto é, o método `load()` permite passar parâmetros para o construtor do serviço e esta seria uma das diferentes formas de fazer isto. 

Você pode usar `setters` e `getters` também, ou seja, o fato de você não acessar diretamente o model na camada de serviços, não te impede de manipular e consumir dados em serviços.

Espero ter ajudado.
Forte abraço e sucesso sempre!

PS: Seria legal você postar esse serviço depois no Github! Outras pessoas podem precisar das mesmas funções!
