### ISSUE TITLE
Alterar Menu

### ISSUE THREAD

**Issue by erickmourasilva** [brunosantoshx/hxphp#135]
Gostaria de alterar o menu e as classes para um menu vertical do bootstrap, como eu poderia proceder?
Localizei onde fica definido as classes bootstrap para gerar o menu, mas está bem confuso de alterar.

**Comment by brunosantoshx** [comment]
Olá @erickmourasilva, boa noite. Tudo bem?

Todas as configurações disponíveis estão descritas na documentação (https://github.com/brunosantoshx/hxphp-docs/blob/master/08-helpers.md) e são inseridas no arquivo `app/config.php`.

Forte abraço e sucesso sempre!
