### ISSUE TITLE
Erro no metodo "$post" com campo "select multiple"

### ISSUE THREAD

**Issue by FilippeMafra** [brunosantoshx/hxphp#136]
Boa noite,
(pesquisei em #125 e não resolvi)
Não consegui capturar no "$post" um campo "<select multiple>". Está retornando "=> boolean false" quando executo "var_dump($post)".

**Comment by Lesnock** [comment]
@FilippeMafra , Bom dia!
Se você estiver tentando recuperar um campo _array_ você precisa utilizar o filtro **FILTER_FORCE_ARRAY** neste campo.
Você fez isso?

**Comment by FilippeMafra** [comment]
Deu certo!

Utilizei o exemplo:
`class ProdutosController extends \HXPHP\System\Controller
{
    public function salvarAction()
    {
        $this->request->setCustomFilters([
            'id' => [
                'filter' => FILTER_SANITIZE_NUMBER_INT,
                'flags' => FILTER_FORCE_ARRAY
            ]
        ]);
    }
}`
Da documentação [hxphp-docs/09-http.md](https://github.com/brunosantoshx/hxphp-docs/blob/328795b4bb7196a4d2704e1a446c29676327e7d1/09-http.md).
Obrigado.
