### ISSUE TITLE
Como ficaria uma classe comum de conexao ?

### ISSUE THREAD

**Issue by davidsonhr1** [brunosantoshx/hxphp#137]
Boa noite, 

Como ficaria uma classe comum de conexão com mysql por exemplo ?

usando um Banco de dados ja existente

usando o sistema de autoload

**Comment by gabriel-caruso** [comment]
Crie a sua classe PDO de conexão com MySQL e acresente a classe à sessão `autoload` > `psr-4` do `composer.json`. Não se esqueça de usar `namespace` nesta classe!
