### ISSUE TITLE
Model sem Active ORM

### ISSUE THREAD

**Issue by kinzinho666** [brunosantoshx/hxphp#138]
Como fica caso eu não queria utilizar os padrões do Active, queira digitar minhas querys do meu jeito, tableas e campos sem seguir os padrões estipulados?

**Comment by gabriel-caruso** [comment]
Olá @kinzinho666 

Acredite que você esteja procurando pelo método [`query`](http://www.phpactiverecord.org/docs/ActiveRecord/Model#methodquery) do Model que você esteja trabalhando.
