### ISSUE TITLE
Erro first commit

### ISSUE THREAD

**Issue by aguiauno** [brunosantoshx/hxphp#146]
$ git commit -m "First commit"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Admin@Admin-PC.(none)')
como se resolve isso, please!

**Comment by flemej** [comment]
Ótimo guia para git:
http://rogerdudler.github.io/git-guide/index.pt_BR.html

**Comment by aguiauno** [comment]
Obrigado flemej já resolvi agora tó trancado nesse aqui:
Fatal error: Uncaught Error: Class 'HXPHP\System\Configs\Config' not found in C:\wamp\www\sistema\app\config.php:3 Stack trace: #0 {main} thrown in C:\wamp\www\sistema\app\config.php on line 3

**Comment by flemej** [comment]
Se  a sua linha 3 for igual a "$configs = new HXPHP\System\Configs\Config;", você tem um problema na instalação do framework. Reveja os procedimentos descritos na documentação ou nos vídeos do youtube.

**Comment by aguiauno** [comment]
Sim está igual, me diz uma coisa não tem  como corrigir isso manualmente,
outra coisa vou perder todas as configurações ffeita até agora? pois é este
erro que tá dando quando chamo http://localhost/sistema/app/config.php
*Fatal error*: Uncaught Error: Class 'HXPHP\System\Configs\Config' not
found in C:\wamp\www\sistema\app\config.php:3 Stack trace: #0 {main} thrown
in *C:\wamp\www\sistema\app\config.php* on line *3 *este erro está
relacionado a isso: http://localhost/sistema/cadastro/cadastrar
*Fatal error*: Uncaught ActiveRecord\DatabaseException: PDOException:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sistemahx.users'
doesn't exist in
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php:333
Stack trace: #0
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(333):
PDOStatement->execute(Array) #1
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\adapters\MysqlAdapter.php(25):
ActiveRecord\Connection->query('SHOW COLUMNS FR...') #2
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(275):
ActiveRecord\MysqlAdapter->query_column_info('`users`') #3
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(402):
ActiveRecord\Connection->columns('`users`') #4
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Cache.php(73):
ActiveRecord\Table->ActiveRecord\{closure}() #5
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(402):
ActiveRecord\Cache::get( in
*C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php*
on
line *336 😢*

2017-10-15 2:18 GMT-02:00 Fabio LJ <notifications@github.com>:

**Comment by flemej** [comment]
Com esse erro, deu pra ter bem mais ideia do que está acontecendo. O erro aponta que a sua tabela users não existe.  Se a tabela existir com o nome "users" (e não "user"), é provável que o seu model  esteja com o nome errado. O nome do model deve ser o singular do nome da tabela. Verifique esses pontos e se não enviar nenhum erro, poste o seu código aqui pra gente poder analisar.

**Comment by aguiauno** [comment]
ok. blza vou verificar. Muito obrigado pela sua atenção!


Em 15 de outubro de 2017 13:44, Fabio LJ <notifications@github.com>
escreveu:

**Comment by aguiauno** [comment]
Bom aproveitei para corrigir uns erros no código. Na modelagem constava
tb_users modifiquei para  users tentei cadastrar de novo e tai outro erro,
coisa mais complicadaa minha nossa...
*Fatal error*: Uncaught ActiveRecord\DatabaseException: PDOException:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for
column 'password' at row 1 in C:\wamp\www\sistema\vendor\
php-activerecord\php-activerecord\lib\Connection.php:333 Stack trace: #0
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(333):
PDOStatement->execute(Array) #1 C:\wamp\www\sistema\vendor\
php-activerecord\php-activerecord\lib\Table.php(359):
ActiveRecord\Connection->query('INSERT INTO `us...', Array) #2
C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Model.php(844):
ActiveRecord\Table->insert(Array) #3 C:\wamp\www\sistema\vendor\
php-activerecord\php-activerecord\lib\Model.php(799):
ActiveRecord\Model->insert(true) #4 C:\wamp\www\sistema\vendor\
php-activerecord\php-activerecord\lib\Model.php(780):
ActiveRecord\Model->save(true) #5 C:\wamp\www\sistema\app\models\User.php(17):
ActiveRecord\Model::create(Array) #6
C:\wamp\www\sistema\app\controllers\CadastroController.php(12):
User::Cadas in
*C:\wamp\www\sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php*
on
line *336*

Em 15 de outubro de 2017 13:44, Fabio LJ <notifications@github.com>
escreveu:

**Comment by aguiauno** [comment]
Esse erro mostrado a seguir mostra que o campo da tabela password tem tamanho insuficiente para gerar a senha usando shahx: *Fatal error*: Uncaught ActiveRecord\DatabaseException: PDOException:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for
column 'password' at row 1 in. Solução aumente o numero de caracteres suportados exemplo: 128 para 220 problema resolvido usando php7 e mysql 5.
