### ISSUE TITLE
Gostaria de um exemplo para o uso de view parciais

### ISSUE THREAD

**Issue by Davidsonc** [brunosantoshx/hxphp#147]
@brunosantoshx como se usa essa funcionalidade ? elas podem ser carregadas dentro de divs dentro de uma view como um retorno de ajax ?

**Comment by brunosantoshx** [comment]
Olá @Davidsonc, como vai?

O recurso de views parciais é a solução para o desenvolvimento modular, isto é, você pode quebrar o código da sua view em vários arquivos segmentados. Quais as vantagens? Reutilização de código e Organização!

Você poderá chamar os módulos em quaisquer views e também passar variáveis.

No caso do retorno do ajax: Você poderá colocar um módulo oculto que só é exibido quando a requisição procede e traz a resposta necessária.

Abs!
