### ISSUE TITLE
HXPHP no linux

### ISSUE THREAD

**Issue by pcampello** [brunosantoshx/hxphp#15]
Fala Bruno blz?

Cara passei um projeto com hxphp para o linux e quando fui executar o apache não estava localizando algumas views.

Acabei notando que era em função do case sensitive.

Dei uma olhada em algumas classe do hxphp e notei que na classe da view, a logica para localizar a view é pegar o nome do controller e retirar a string Controller, e depois converter tudo para minúsculo.

Tenho uma view que ta dentro da pasta cadastroUnidade, neste caso estava procurando por cadastrounidade e não localizava.

Tive que altera a classe view.php para localizar minha view.

É isso mesmo ou teria outra maneira de fazer?

**Comment by brunosantoshx** [comment]
Olá @pcampello, tudo ótimo e contigo?

O padrão das views é lowercase, ou seja, tudo minúsculo. O certo mesmo é renomear as views para se adequarem ao padrão, pois, alterar estas classes principais poderá te proporcionar dores de cabeça em uma futura atualização do framework ou o trabalho em equipe.

**Comment by pcampello** [comment]
Certo, farei isso então.

Valeu!
