### ISSUE TITLE
desuso específico do header.php e footer.php

### ISSUE THREAD

**Issue by lucassousa25** [brunosantoshx/hxphp#152]
Como faço para não usar o header.php e o footer.php em somente uma view.
No meu caso a minha view de login não seguirá o padrão das outras, queria que ela ficasse sem o header.php e o footer.php, mas usarei eles nas outras views.

**Comment by flemej** [comment]
Da uma olhada na documentação do framework!
https://github.com/brunosantoshx/hxphp-docs/blob/master/06-views.md

Se ainda tiver dúvidas, poste aqui! :)

**Comment by lucassousa25** [comment]
Sanei minhas dúvidas, Obrigado!
