### ISSUE TITLE
Postgres

### ISSUE THREAD

**Issue by anepriscila** [brunosantoshx/hxphp#156]
e possivel utilizar o HXframework com Postgres?

**Comment by skay1994** [comment]
O ORM do banco de dados, se nao me engano suporta, nessa pagina em Multi-connections mostra um exemplo http://www.phpactiverecord.org/projects/main/wiki/Configuration__Setup

**Comment by brunosantoshx** [comment]
Olá @anepriscila e @skay1994, tudo bem?

É como o @skay1994 disse: O ORM permite definir qual é o `driver` e isto também é definido no arquivo `app/config.php`.

```php
$configs->env->development->database->setConnectionData([
    'driver' => 'mysql',
    'host' => 'localhost',
    'user' => 'root',
//...
]);
```
Forte abraço e sucesso sempre!
