### ISSUE TITLE
Validação de Cadastro por Email

### ISSUE THREAD

**Issue by juanlandim** [brunosantoshx/hxphp#16]
Uma sugestão para o sistema de login ficar ainda melhor é mais seguro seria uma validação de cadastro via Email onde o usuário só teria acesso quando validasse sua conta via E-mail em um link que é gerado automaticamente pelo sistema.

**Comment by gilglecio** [comment]
Outra Solução seria a validação em duas etapas.

**Comment by michaelmdxt** [comment]
isso seria muito bom para podermos utilizar pra um filtro de pessoas realmente interessadas em no produto ou conteudo que seria disponibilizados na suposta lista

**Comment by brunosantoshx** [comment]
Fala galera! 

Pretendo adicionar esta funcionalidade durante as aulas extras. Ainda temos muita coisa para fazer no escopo original da série.

Sei que estou demorando para postar novas aulas, mas é que estou passando por um momento muito caótico que não está me dando folga, porém creio que logo conseguirei conciliar as minhas novas responsabilidades e retomar com força total ao canal.

Forte abraço e sucesso sempre!
Fala galera! 

Pretendo adicionar esta funcionalidade durante as aulas extras. Ainda temos muita coisa para fazer no escopo original da série.

Sei que estou demorando para postar novas aulas, mas é que estou passando por um momento muito caótico que não está me dando folga, porém creio que logo conseguirei conciliar as minhas novas responsabilidades e retomar com força total ao canal.

Forte abraço e sucesso sempre!
