### ISSUE TITLE
Trim() no retorno de ActiveRecord

### ISSUE THREAD

**Issue by pcampello** [brunosantoshx/hxphp#17]
Olá,

Quando eu uso o ActiveRecord para buscar alguma informação do tipo string do banco, está retornado uma string do tamanho total do campo.

Por exemplo:
Tenho um campo char(10) chamado name na tabela user.
Quando faço "user::find_by_id(1)->name" retorna o nome do usuário com espaços, ou seja, 
se o nome do usuário é "Pedro" está retornando "Pedro     ".

OBS: estou usando banco Postgresql

Não sei se estou fazendo de forma correta, não sei se o problema está no ActiveRecord não sei se o problema está em alguma classe, enfim, gostaria de saber uma forma de resolver de modo que eu não precise usar a função trim() toda hora que usar ActiveRecord.

Obrigado.

**Comment by brunosantoshx** [comment]
Olá @pcampello 

Bem estranho isto! Tem certeza que a informação salva no db não tem nenhum espaço?

**Comment by pcampello** [comment]
Só para deixar documentado, descobri o problema dos espaços em brancos, o motivo era pelo fato de eu estar usando o tipo char() nos campos do banco, sendo que o tipo char() pelo menos no postgre não sei dizer nos outros é um tipo de dado fixo, ou seja char(10) vai conter 10 caracteres mesmo que a informação gravada contenha 3 caracteres.
Enfim, para resolver o problema usei o tipo varchar() que é variável.
