### ISSUE TITLE
Permitir ícone (awesome) para sub-menu em Helpers/Menu

### ISSUE THREAD

**Issue by pcampello** [brunosantoshx/hxphp#18]
E aí Bruno blz?

Tava pensando em criar uma PR para permitir ícones awesome nos sub-menus também o que acha?

Outra coisa, para minha necessidade criei uma classe CustomMenu que desenvolvi a partir da classe Menu, e nessa classe CustomMenu a cada chamada do método  setHTML() eu precisei zerar (null) o atributo this->html. Na classe Menu você apenas incrementa o atributo html (linha 89), acredito que deva ter um motivo para tal, mas pergunto, caso eu faça a PR dos ícones nos submenus posso zerar o atributo html ou deixo como está hoje?

Valeu, abraço.

**Comment by brunosantoshx** [comment]
Opa @pcampello! Tudo ótimo :)

A mecânica atual deste Helper é gerar todo o HTML em uma única vez, portanto o atributo `html` é incrementado.

A sua ideia é bem bacana e não vejo problema algum em ter outra lógica. Crie o PR e vamos trabalhar juntos nesta feature para que ela entre na próxima versão do HXPHP.

Forte abraço e sucesso sempre!
