### ISSUE TITLE
Como trabalhar com novos arquivos (header, footer) e pastas (css, js)

### ISSUE THREAD

**Issue by washingtoncardoso** [brunosantoshx/hxphp#19]
Além dos arquivos e pastas default do hxphp, preciso adicionar novos arquivos (header, footer) e pastas (css, img, js). Como proceder?

**Comment by brunosantoshx** [comment]
Olá @washingtoncardoso, como vai?

O HXPHP tem suporte para header e footer customizados, sendo assim, você pode usar os métodos `setHeader()` e `setFooter()` do objeto `View`.

A pasta `public` tem a finalidade de armazenar todos os arquivos públicos, isto é, estas pastas (css, img e etc) devem ser subdiretórios da pasta `public`.

**Comment by washingtoncardoso** [comment]
Olá @brunosantoshx, muito obrigado!

Após alguns tentativas a dúvida foi sanada, ficou mais ou menos assim:

public function indexAction()
    {
        $this->view->setPath('login')
            ->setFile('index')
            ->setHeader('headerAdm')
            ->setFooter('footerAdm')
            ->setTemplate(true)
            ->setTitle('Bem-vindo');
    }
