### ISSUE TITLE
Erro ao criar tabela

### ISSUE THREAD

**Issue by castiel6666** [brunosantoshx/hxphp#2]
Olá, estou seguindo um tutorial de cadastro e ao tentar criar a tabela no mysql recebo um erro de sintaxe, mas eu digito exatamente o que o tutorial pede e ainda assim recebo esse erro. Alguém ai tem alguma ideia do que seja? a versao do mysql é 5.6.17. Desde já agradeço
http://i.imgur.com/Hzw7YKN.png

**Comment by brunosantoshx** [comment]
Olá, como vai?

O problema é de sintaxe realmente, pois o comando é `create` e você colocou "creat".

Espero ter ajudado :)

Bons estudos e sucesso sempre!
Obs: Esta dúvida deveria ter sido publicada no repo da série.
