### ISSUE TITLE
Argumentos indexAction()

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#20]
Olá Bruno, como passou o final de ano?

Primeiramente um Feliz Natal e um Feliz ano novo (atrasados :sweat_smile:), e que tenhamos um ano cheio de linhas de códigos para digitar :grin:

Bruno, recentemente passei pela seguinte necessidade: passar argumento a `indexAction()`, porém não consegui. Teria como me ajudar?

Ex: `meuwebsite.com/noticias/chuvas_aumentam_niveis_reservatorios`
- `notícias` seria o meu Controller
- `chuvas_aumentam_niveis_reservatorios` seria meu argumento (titulo da notícias, por exemplo)

Desde já, muito obrigado!

**Comment by brunosantoshx** [comment]
Olá @carusogabriel, passei bem, graças à Deus, e você?

Opa mano, idem kkkkk.

Infelizmente isto não é possível, de ser feito, com a estrutura atual do HXPHP. O framework ainda não conta com um recurso de rotas e, portanto, define estaticamente os valores mediante a ordem da URL. 

A única solução é incluir uma `action` na URL. 

Obs: Eu não sei até onde é válido a implementação do recurso de rotas no framework, pois a ideia é de simplificar ao máximo.

Forte abraço e sucesso sempre!
