### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by EduardoCastro2016** [brunosantoshx/hxphp#21]
Boa noite, estou gostando bastante das aulas, mas estou com um probleminha, quando coloco Localhost/sistema, entra normal nesta tela: http://tinypic.com/r/2a6jyib/9, agora quando eu coloco Localhost/sistema/Cadastro, ou qualquer outro link não existente aparace somente esta tela: http://tinypic.com/r/4kfps3/9

**Comment by brunosantoshx** [comment]
Olá @EduardoCastro2016, como vai?

Este problema é bem comum e já foi abordado aqui nas issues: https://github.com/brunosantoshx/hxphp/issues/8.

Por favor, leia esta issue e siga atentamente as instruções que conseguirá colocar o sistema pra rodar perfeitamente :)

Forte abraço e sucesso sempre!
