### ISSUE TITLE
Validação de dados no update_attributes()

### ISSUE THREAD

**Issue by pcampello** [brunosantoshx/hxphp#23]
Olá pessoal, 
Estou com uma dúvida na atualização de registros.

Pelo que entendi o padrão do HXPHP seria criar um model e dentro desse model criar os métodos de CRUD. Pois bem, tenho um model de usuário e nesse model tenho algumas validações, porem algumas dessas validações servem apenas para o create, para o update não, vamos ao exemplo.

Tenho o model usuário e nesse model umas das validações é validates_uniqueness_of da matricula. Essa validação da matricula ser única só pode ser feita no create no update não, pois se eu alterar somente o nome do usuário, quando eu fizer o update_attributes ou save() vai retornar o erro que a matrícula já existe(claro).

Além disso no model usuário também tem a validação de validates_presence_of para o campo matricula.

Ou seja, se eu retirar o atributo matrícula e executar o update_attributes() vai retornar erro informando que o campo é obrigatório, se eu não retirar o atributo matrícula vai retornar erro que o campo matrícula já existe.

Gostaria de saber qual a maneira correta de atualizar dados realizando "quase" as mesmas validações do create.

Desde já agradeço.

Att,
Paulo Campello

**Comment by brunosantoshx** [comment]
Olá @pcampello, como vai?
Esse assunto foi tratado na aula 8 da atual série do canal. Você pode usar o parâmetro `on` no caso da validação `validates_presence_of`, porém já para a `validates_uniqueness_of` infelizmente o mesmo recurso não existe e isto ocasiona esta dor de cabeça. Uma alternativa é passar um booleano `false` no método `save` para pular as validações do `update`.
