### ISSUE TITLE
Criar metodo disponível para todos os Models (formatação de data)

### ISSUE THREAD

**Issue by pcampello** [brunosantoshx/hxphp#24]
Olá,

Estou com uma dúvida quanto ao tratamento de datas.

Pensei em criar um método que eu possa acessar em todos os models para tratar as datas, método simples onde eu passo a data no formato brasileiro e retorna a data no formato do BD e vise-versa.

Atualmente estou criando um método em cada Model que eu preciso para fazer tal ação porem gostaria de saber a melhor maneira para fazer isso, na minha opinião seria um método acessível em todos os Models, mas se existir outra solução por favor comentem.

Obrigado,

Att,

Paulo Campello

**Comment by brunosantoshx** [comment]
Olá @pcampello, como vai?
Você pode criar um `model` específico para tal funcionalidade, porém este não pode herdar a classe mestre `Model` e motivo é que quando o `model` herda tal classe, o mesmo se torna componente ORM.
