### ISSUE TITLE
hxphp oci driver transaction commit rollback

### ISSUE THREAD

**Issue by pazini** [brunosantoshx/hxphp#27]
Ola Bruno!

Estou usando seu framework e aqui nós usamos ORACLE. Para isso estou trabalhando com o driver OCI.

Vi no site so Active Record que posso trabalhar com transaction, porém fiquem em dúvida de como implementar isso no HXPHP!

Podes me ajudar?!

http://www.phpactiverecord.org/boards/4/topics/644-db-transactions-in-php-activerecord

			try {
			     $c1->transaction();
			     $c2->transaction();
			     // SQL…
			     // SQL…
			     // SQL…
			     $c1->commit();
			     $c2->commit();
			 } catch (\Exception $e) {
			     $c1->rollback();
			     $c2->rollback();
			     throw $e;

**Comment by brunosantoshx** [comment]
Olá @pazini, como vai?

Você pode usar livremente todos os recursos do PHP AR no HXPHP. Basicamente, para o uso de transações, você pode seguir este exemplo que postou ou conferir o exemplo oficial:
http://www.phpactiverecord.org/docs/ActiveRecord/Model#methodtransaction

Forte abraço e sucesso sempre!

**Comment by pazini** [comment]
Bruno...

muito obrigado pelo retorno imediato!

Em tempo: É possível o uso de Procedures do Oracle?!

Sds,
Pazini



Em 29 de abril de 2016 00:01, Bruno Campos Santos <notifications@github.com>
escreveu:
