### ISSUE TITLE
Ao colocar em pastas os "services", seu sistema parou de funcionar.

### ISSUE THREAD

**Issue by luanribeiross** [brunosantoshx/hxphp#30]
Ao colocar as classes services em pastas e chamar no index por elas, seu sistema parou de funcionar no linux ubuntu com xampp:

Fatal error: Class 'HXPHP\System\Services\StartSession' not found in /opt/lampp/htdocs/sistema/index.php on line 26
não sei por que...

**Comment by brunosantoshx** [comment]
Olá @luanribeiross, como vai?

Nesta versão, o index.php também foi alterado. Se clonar o repositório no branch master poderá utilizar sem problema algum.

Forte abraço e sucesso sempre!

**Comment by luanribeiross** [comment]
Amigo, ainda não consegui rodar. No windows a mesma coisa:
Se eu digito: localhost/sistema/asas

Ele retorna o erro padrão abaixo, ao invés da sua página "not found" customizada. Está correto isso? Eu reinstalei do zero: Download as zip, composer install,

Ele se comporta assim sem nenhuma modificação na pasta app e com a antiga tb. É normal?

_________________________________________________________________________
Objeto não encontrado!

A URL requisitada não foi encontrada neste servidor. Se você digitou o endereço (URL) manualmente, por favor verifique novamente a sintaxe do endereço.

Se você acredita ter encontrado um problema no servidor, por favor entre em contato com o webmaster.
Error 404
localhost
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.20

**Comment by brunosantoshx** [comment]
Creio que seu .htaccess e/ou app/config.php estejam desconfigurados

**Comment by luanribeiross** [comment]
Rapaz era isso mesmo. Funcionou. Parabéns por esse trabalho magnífico rapaz. Vc não deve nada e mesmo assim responde com paciência super rápido. Fantástico seu trabalho.

Porém agora coloquei os models, controllers e views antigas e obtive: :( 
http://oi64.tinypic.com/a4qxdg.jpg

**Comment by brunosantoshx** [comment]
Opa, obrigado! O meu objetivo é que todos possam participar do projeto HXPHP e tenham, ao menos, um commit como participação. Quero ter o orgulho de dizer que é o framework desenvolvido pelo canal HXTUTORS e não pelo Bruno ou Fulano. E, para isso, estarei sempre por aqui para esclarecer todas as dúvidas e sempre incentivar à todos!

Sobre o print... O link está quebrado hehehehee

**Comment by luanribeiross** [comment]
Já saquei o lance.. 

O problema era:
""
Fatal error: Uncaught exception 'Exception' with message 'Verifique as configuracoes de autenticacao para a subpasta: < default >' in /opt/lampp/htdocs/sistema/src/HXPHP/System/Services/Auth/Auth.php:54 Stack trace: #0 [internal function]: HXPHP\System\Services\Auth\Auth->__construct(NULL, NULL, true) #1 /opt/lampp/htdocs/sistema/src/HXPHP/System/Controller.php(106): ReflectionClass->newInstanceArgs(Array) #2 /opt/lampp/htdocs/sistema/app/controllers/LoginController.php(15): HXPHP\System\Controller->load('Services\\Auth', NULL, NULL, true) #3 /opt/lampp/htdocs/sistema/src/HXPHP/System/App.php(90): LoginController->__construct(Object(HXPHP\System\Configs\Config)) #4 /opt/lampp/htdocs/sistema/index.php(31): HXPHP\System\App->run() #5 {main} thrown in /opt/lampp/htdocs/sistema/src/HXPHP/System/Services/Auth/Auth.php on line 54
""
Resolvi trocando:
    'Services\Auth'
para: 
    'Services\Auth\Auth'
no construtor dos controllers. Valeu.
