### ISSUE TITLE
redirectCheck não está funcionando

### ISSUE THREAD

**Issue by caiorcferreira** [brunosantoshx/hxphp#31]
Boa noite, eu estou acompanhando o projeto do Sistema de cadastro e login com níveis de acesso através do canal HxTutors no youtube.

Na video-aula 7 configura-se o sistema de autenticação e o implementa no controller da página de cadastro. Contudo, caso o rediredctCheck fosse definido como falso, ao tentar acessa a página de cadastro eu deveria ser direcionado à página de login (que está funcionando normalmente se acessada diretamente através da URL). 

Alguém poderia ajudar?
Caso seja necessário ver algum código avise-me qual.

Obrigado!

**Comment by brunosantoshx** [comment]
Olá @caiorcferreira, como vai?

Primeiramente, o ideal seria que esta issue fosse publicada no repositório da respectiva série para que outros alunos pudessem lhe ajudar e também compartilharem da solução juntamente contigo. 

E, sobre a dúvida, creio que houve algum engano, pois o código no CadastroController é : `$this->auth->redirectCheck(true);`, ou seja, o parâmetro `public_page` é `true`.

Forte abraço e sucesso sempre!
