### ISSUE TITLE
Invertendo o mes com o dia na hora de salvar data

### ISSUE THREAD

**Issue by pazini** [brunosantoshx/hxphp#33]
Bruno... Ajudaaaa

Eu estou enviando a data correta para o banco 
DateTime Object
(
    [date] => **2011-12-11** 01:51:37.000000
    [timezone_type] => 3
    [timezone] => America/Sao_Paulo
)

E ele insiste em salvar:

[model:ActiveRecord\DateTime:private] => Unidades Object
 *RECURSION*
                            [attribute_name:ActiveRecord\DateTime:private] => data_protocolo
                            [date] => **2011-11-12 00:00:00.000000**
                            [timezone_type] => 2
                            [timezone] => BRST

**Comment by brunosantoshx** [comment]
Olá @pazini, como vai?

Este é o formato padrão para datas. E você pode salvar tranquilamente desta forma e depois converter na hora de exibir. Tanto é que este formato lhe auxilia nas consultas por datas, tais como: relatórios e semelhantes.

Para converter:
```php
echo date('d-m-Y', strtotime($item->created_at));
```
Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Acrescentando: você pode colocar qualquer formato de data dentro do argumento da função `date()`. Exemplos: d/m/Y ou Y-m-d e etc
