### ISSUE TITLE
Melhorias do Framework HXPHP

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#34]
@brunosantoshx, boa tarde, como vão as coisas?

Gostaria de deixar algumas ideias de melhorias para o HXPHP que pensei recentemente, mas acho melhor lista-las antes para ti analizar, antes de submeter os PRs. Aqui estão algumas delas:

- Adição da Classe [PHPMailer](https://github.com/PHPMailer/PHPMailer) para envio de e-mails de forma mais segura e profissional;
- Atualização do Framework para a versão 7 do PHP, que conta com melhorias significativas e velocidade, alguns operadores lógicos melhorados, e algumas formas de declaração de `use` em forma de arrays, que nos polparia algumas linhas de processamento;
- Remoção das `{}` em alguns `if`, `else`, `foreach`, quando apresentarem apenas uma linha de comando após a instrução, o que polpa algum processamento também.

Na classe `Auth`, tenho algumas ideias:
- No método `login()`, adicionar um 3º parâmetro, chamado `remember`, um `bool`, que guardaria a opção do usuário se manter logado, como no Facebook existe o `Mantenha-me conectado`;
- No método `logout()`, adicionar um loop para remoção de todos os cookies, e usar a função ` session_unset()`, que remove todas as variáveis de sessão;
- Voltarmos o método `role_check()` que existia em versões antigas do HXPHP, que é bastante util quando existem vários níveis de acesso.

E outra melhoria, mas não consegui pensar num algoritmo para isto, seria a possibilidade de adicionar mensagens (Com o `Helpers\Alert`) em páginas redirecionadas, por exemplo: após o login, no index seria mostrado uma mensagem de boas vindas.

Bem, por hora é só. Espero que goste das ideias e que eu possa contribuir um pouco com a comunidade. Qualquer dúvida, meu email se encontra na minha página do GitHub.

Só uma ultima dúvida: recentemente, acompanhando os seus commits, percebi algumas modificações de pastas, para a criação do `admin`. Isto será apresentado em aula, ou será gerado uma parte nova na documentação?

Abraços,

[Gabriel Caruso](https://github.com/carusogabriel)

**Comment by brunosantoshx** [comment]
Olá @carusogabriel, boa tarde. Tudo ótimo e melhor agora!

Você tem conta no Trello? Gostaria de te colocar no projeto para você ficar por dentro de todos os próximos passos de melhorias no HXPHP assim como você também registrar todas estas melhorias e as outras que surgirem. Caso se interesse, por favor, poste aqui o seu nome de usuário do Trello.

Gostei de todas as propostas, porém a única que me preocupa é a atualização para PHP7. Mas, podemos criar uma validação de versão e além de exibir uma mensagem de erro também colocar um link de um tutorial para ajudar a pessoa no processo de atualização. O que acha?

Quanto ao uso do `AlertHelper` para redirecionamentos, creio que o uso de `storage` seja uma boa opção. Podemos salvar o alert em uma SESSION e retirar a obrigatoriedade do array no construtor mediante a existência de uma SESSION. Apenas uma ideia, depois podemos refinar.

Esta melhoria foi muito solicitada que é a possibilidade de separar os controllers e views em subpastas, isto é, agora para criar um administrativo + site não precisa de dois HXPHPs ou de confusão na nomenclatura é só criar uma subpasta admin que está tudo resolvido.

A documentação está sendo convertida para MARKDOWN neste repo: https://github.com/brunosantoshx/hxphp-docs. Estou adicionando todas as novas funcionalidades nesta nova versão da documentação. Assim que eu terminar a conversão, vou atualizar a documentação do site. Com a documentação também no Github será possível que os responsáveis pelas melhorias do framework também adicionem as instruções de uso na documentação. 

Agora é só programar! 
Fico no aguardo.
Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Uma observação: Sempre que for possível, o ideal é que as nossas melhorias não inutilizem o código de quem já fez um sistema com as versões antigas. E, se não existir outra opção, o ideal é que detalhemos na release todo o passo a passo para adaptar. Um exemplo é o uso do PHPMailer. Podemos adicionar como um novo serviço, mas não podemos substituir pelo serviço atual que já é utilizado pelos usuários. Estou empolgado com estas melhorias! A comunidade vai pirar! Tamo junto, brother!

**Comment by carusogabriel** [comment]
Perfeito, entendi.

Ainda esta semana postarei os PRs, e caso inutilize algo existente no Framework, você me dá um toque que repenso o algoritmo!
