### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#4]
Ola, tudo bem?

Como manipular o erro `403` (permissão) para gerar uma página igual a `404`?

Obrigado, e parabéns pelo trabalho!

**Comment by brunosantoshx** [comment]
Olá, tudo sim e contigo?

Ainda não existe uma solução nativa para customizar a página deste erro, porém você pode construí-la e definir o link através do `.htaccess`.

Exemplo:
`ErrorDocument 403 /sistema/index.php?status=403`

**Comment by carusogabriel** [comment]
Tudo na santa paz!

Entendi o raciocínio, e estou manipulando o erro na `indexAction()` do `Error404Controller`.

Como eu poderia atribuir um `%s` no lugar de `<h4>Ops! Nada encontrado!</h4>` no `index.phtml` do `error404` e modificar-lo na `indexAction()` conforme erros: `404`, `403`, `500`, etc?

Desde já, agradeço pela paciência!

**Comment by brunosantoshx** [comment]
Show :)

Entendi. Agora sobre sua dúvida:

Acho que o ideal é você passar uma variável para a view `$view_mensagem` e alterar o valor dela de acordo com o erro na  `indexAction()`.

**Comment by carusogabriel** [comment]
Solução perfeita!

Muito obrigado!
