### ISSUE TITLE
Arquivo EnvironmentDevelopment.php

### ISSUE THREAD

**Issue by consule** [brunosantoshx/hxphp#42]
Bruno, 

Provavelmente tem um erro na linha 14 deste arquivo. 

`		$this->servers = [`
Estou estudando baseado nas video aulas que você coloca no Youtube e acredito que esta seria:
`		$this->servers = array[`

**Comment by brunosantoshx** [comment]
Olá @consule, como vai?

Poderia me dizer qual erro está sendo reportado? Este arquivo foi atualizado para suportar recursos do PHP 5.4+. Um dos recursos é a notação simplificada para arrays.

**Comment by consule** [comment]
Nenhum erro esta sendo exibido. É que na video aula é exibidoassim
`$this->servers = array[`

e no arquivo atualizado exibe que baixei hoje esta assim: 
`$this->servers = [`

Se esta certo tudo bem. Estou fazendo a seria de videos do sistema de login usando o seu Framework

**Comment by brunosantoshx** [comment]
Ah sim, compreendo. De toda forma, muito obrigado pelo feedback. Sucesso na série e qualquer dúvida é só postar aqui.

Forte abraço e sucesso sempre!
