### ISSUE TITLE
uma notice aparecendo bem na tela inicial

### ISSUE THREAD

**Issue by marceloiavenissi** [brunosantoshx/hxphp#44]
Olá, primeiramente quero parabenizar pelo trabalho, excelente, bom estou iniciando php e gostei muito dos tutoriais do canal porem logo no primeiro teste do framework apareceu uma nota do php segue o código html:

<table class="xdebug-error xe-notice" dir="ltr" border="1" cellpadding="1" cellspacing="0">
<tbody><tr><th colspan="5" align="left" bgcolor="#f57900"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Notice: Undefined index: default in C:\wamp\www\sistema\src\HXPHP\System\Helpers\Menu\Render.php on line <i>46</i></th></tr>
<tr><th colspan="5" align="left" bgcolor="#e9b96e">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td align="center" bgcolor="#eeeeec">1</td><td align="center" bgcolor="#eeeeec">0.0019</td><td align="right" bgcolor="#eeeeec">137680</td><td bgcolor="#eeeeec">{main}(  )</td><td title="C:\wamp\www\sistema\index.php" bgcolor="#eeeeec">..\index.php<b>:</b>0</td></tr>
<tr><td align="center" bgcolor="#eeeeec">2</td><td align="center" bgcolor="#eeeeec">0.2853</td><td align="right" bgcolor="#eeeeec">1168712</td><td bgcolor="#eeeeec">HXPHP\System\App-&gt;run(  )</td><td title="C:\wamp\www\sistema\index.php" bgcolor="#eeeeec">..\index.php<b>:</b>33</td></tr>
<tr><td align="center" bgcolor="#eeeeec">3</td><td align="center" bgcolor="#eeeeec">0.3139</td><td align="right" bgcolor="#eeeeec">1269432</td><td bgcolor="#eeeeec">HXPHP\System\View-&gt;flush(  )</td><td title="C:\wamp\www\sistema\src\HXPHP\System\App.php" bgcolor="#eeeeec">..\App.php<b>:</b>108</td></tr>
<tr><td align="center" bgcolor="#eeeeec">4</td><td align="center" bgcolor="#eeeeec">0.3186</td><td align="right" bgcolor="#eeeeec">1274040</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'C:\wamp\www\sistema\app\views\index\index.phtml'</font> )</td><td title="C:\wamp\www\sistema\src\HXPHP\System\View.php" bgcolor="#eeeeec">..\View.php<b>:</b>268</td></tr>
<tr><td align="center" bgcolor="#eeeeec">5</td><td align="center" bgcolor="#eeeeec">0.3186</td><td align="right" bgcolor="#eeeeec">1274056</td><td bgcolor="#eeeeec">HXPHP\System\Helpers\Menu\Menu-&gt;__toString(  )</td><td title="C:\wamp\www\sistema\src\HXPHP\System\View.php" bgcolor="#eeeeec">..\View.php<b>:</b>8</td></tr>
<tr><td align="center" bgcolor="#eeeeec">6</td><td align="center" bgcolor="#eeeeec">0.3187</td><td align="right" bgcolor="#eeeeec">1274088</td><td bgcolor="#eeeeec">HXPHP\System\Helpers\Menu\Menu-&gt;getMenu(  )</td><td title="C:\wamp\www\sistema\src\HXPHP\System\Helpers\Menu\Menu.php" bgcolor="#eeeeec">..\Menu.php<b>:</b>98</td></tr>
<tr><td align="center" bgcolor="#eeeeec">7</td><td align="center" bgcolor="#eeeeec">0.3187</td><td align="right" bgcolor="#eeeeec">1274448</td><td bgcolor="#eeeeec">HXPHP\System\Helpers\Menu\Render-&gt;getHTML(  )</td><td title="C:\wamp\www\sistema\src\HXPHP\System\Helpers\Menu\Menu.php" bgcolor="#eeeeec">..\Menu.php<b>:</b>89</td></tr>
</tbody></table>

Acho estranho porque fiz todas as configurações e as mudanças nos arquivos, obrigado pela atenção.

**Comment by brunosantoshx** [comment]
Olá @marceloiavenissi, como vai?

Desde já, muito obrigado pelo comentário. 

Sobre o erro: 
Na última versão do HXPHP é exibido um menu por padrão. Para que esse menu funcione corretamente é necessária uma configuração no arquivo `app/config.php`:

```php
	$configs->env->development->menu->setConfigs([
		'container' => 'nav',
		'container_class' => 'navbar navbar-default',
		'menu_class' => 'nav navbar-nav'
	]);
    $configs->env->development->menu->setMenus([
		'Home/home' => '%siteURL%',
		'Subpasta/folder-open' => [
			'Home/star' => '%baseURI%/admin/have-fun/',
			'Teste/home' => '%baseURI%/admin/index/',
		]
	]);
```

Acho que o problema é que estas configurações não foram definidas no seu arquivo de configuração. Você também pode retirar o carregamento do `MenuHelper` nos controllers. Vou providenciar isso para evitar novamente este conflito.

Obrigado pelo feedback.
Forte abraço e sucesso sempre!

**Comment by marceloiavenissi** [comment]
Ok obrigado, funcionou corretamente. Ficou interessante essa novidade eu estive observando e parece que vai dar uma possibilidade bem maior para criação/implementação de subsistemas.
