### ISSUE TITLE
Como resgatar valores do banco e da Session? 

### ISSUE THREAD

**Issue by paulinhoa94** [brunosantoshx/hxphp#45]
Olá Bruno, estou com uma grande dúvida! 
Sou novo na programação, seguir a série e deu tudo certo até o momento que precisei resgatar um valor do banco de dados que seria no caso o nome do usuário e não conseguir. 
Fiz um teste da seguinte forma: 

public function indexAction() {
  $teste = User::find_by_('Thiago Silva');
        var_dump($teste);
}        
retorna todos os valores certinho mas não consigo fazer o desmembramento, como havia dito queria só o nome e não todas as informações.

Outra dúvida que tenho também é quais valores são armazenados nas sessões após efetuar o login? 

Queria exibir na minha views o nome do usuário logado e algumas outras informações contidas no banco de dados.

**Comment by brunosantoshx** [comment]
Olá @paulinhoa94, como vai?

Nós teremos exatamente estes assuntos abordados na próxima aula. Eu já gravei ontem e agora só falta editar e upar no canal. 

Acho que amanhã já teremos este conteúdo disponível e já lhe adianto que é super simples!

Fique de olho no canal.
Forte abraço e sucesso sempre!

**Comment by paulinhoa94** [comment]
Valeu man! =D 
#Sucesso
