### ISSUE TITLE
Continuação da série

### ISSUE THREAD

**Issue by gabiantunes** [brunosantoshx/hxphp#46]
Olá Bruno, gostaria de saber quando sai a continuação da série de login e cadastro, estou dependendo dessa finalização para terminar meu projeto. Obrigada!

**Comment by brunosantoshx** [comment]
Olá @gabiantunes, como vai?

Tive vários problemas, mas consegui gravar a aula ontem. Agora é só renderizar e upar. Acho que amanhã já estará disponível no canal.

Sucesso com teu projeto!
Forte abraço e sucesso sempre!
