### ISSUE TITLE
Como importar css/script para as views?

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#49]
Eu vi na documentação do HXPHP que é só executar aqueles comandos dentro de uma Action, mas como eu devo chamá-lo? Apenas pelo nome? Porque assim, não está funcionando...

Por exemplo:

`$this->view->setAssets('css', 'style.css');`

**Comment by carusogabriel** [comment]
Você deve indicar o caminho completo no segundo parâmetro, por exemplo `public/css/style.css`

**Comment by Davidsonc** [comment]
precisa dar um "echo $add_css" no local desejado ou a inclusão é automática ?

**Comment by flemej** [comment]
Davidson, de uma olhada na documentação que lá explica direitinho como proceder

https://github.com/brunosantoshx/hxphp-docs/blob/master/06-views.md

**Comment by Davidsonc** [comment]
Essa parte eu entendi, só não ficou claro na documentação se preciso chamar esses asserts na view ou se a impressão na view acontece automaticamente.

**Comment by flemej** [comment]
No controller, você precisa fazer:
        $this->view->setpath('caminhodasuaview')
                ->setFile('seuarquivoindex')
                ->setAssets('css', 'caminho/da/sua/folhadestilo.css');

E na view:
echo $add_css;

**Comment by Davidsonc** [comment]
Muito obrigado, eh assim que estou fazendo, vou tentar fazer com que os arquivos sejam adicionados automaticamente sem precisar usar o echo, muito obrigado!
