### ISSUE TITLE
Criar configurações para View

### ISSUE THREAD

**Issue by carusogabriel** [brunosantoshx/hxphp#5]
Olá novamente,

Como seria o processo para se criar configurações iguais ao `$this->view->setTitle()` no método `public function indexAction()` de uma view? Como por exemplo:
- `$this->view->setDescription()`;
- `$this->view->setKeywords()`;

Obs: a váriavel `$view_title` em `header.phtml` é gerada onde? Poderia-se gerar outras como `$view_description`, `$view_keywords`?

**Comment by brunosantoshx** [comment]
Olá Gabriel.

Atualmente não existe uma opção para adicionar estas configurações, de forma correta, no objeto `View`. Para atender ao que você precisa é recomendado que você passe estes dados como variáveis, isto é, através do método `setVars()`.

A variável `$view_title` é adicionada de forma manual no objeto `View`. É possível, porém não é uma técnica recomendada, pois em todas as atualizações seria necessário reescrever estes códigos.
