### ISSUE TITLE
Recuperar dados do PHP ActiveRecords com Array

### ISSUE THREAD

**Issue by duducp** [brunosantoshx/hxphp#50]
Boa tarde, tenho um model com as seguintes linhas:
![screenshot_1](https://cloud.githubusercontent.com/assets/16366240/16046418/ccc3ff6a-3222-11e6-9aba-6b78577713c2.png)

No controller estou fazendo o seguinte:
![screenshot_3](https://cloud.githubusercontent.com/assets/16366240/16048011/d45af0ca-3228-11e6-97e4-9affe73c1613.png)

No meu busca/index.phtml estou chamando da seguinte forma: `<?php echo $view_title; ?>`

Ao executar a ação eu consigo recuperar somente o total de itens encontrados, mas não consido recuperar os dados da tabela. Alguém pode encontrar onde está o erro por favor?

**Comment by duducp** [comment]
Boa tarde depois de muito procurar encontrei  um solução, que está descrita abaixo. Se alguém tiver outro método fique a vontade e comente ai...

Model: nele não realizei nenhuma mudança, está da mesma forma da imagem acima.
Controller: A linha 14 ficou da seguinte forma `$this->view->setVar('busca', $buscando);`

Na minha index.phtml eu chamei da seguinte forma: `<?php echo $view_busca->ads[4]->title; ?>`, onde [4] é o numero da linha do array que foi pesquisado. Ex.: Se na minha pesquisa obtive 5 resultados e quero pegar o titulo do resultado 5, eu coloco dessa forma.
Assim eu poderei fazer um laço de repetição e mostrar todos os resultados encontrados.

**Comment by Davidsonc** [comment]
Foi muito importante você ter comentado aqui pois me ajudou bastante com uma parte do código que postou que não tinha nada a ver com a dúvida que você tinha, que por sinal, também acabei aprendendo pois com certeza enfrentarei uma situação parecida e você mostrou como proceder, muito obrigado!!!
