### ISSUE TITLE
Como usar o "include"?

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#52]
Gostaria de saber como faço para incluir uma página de formulário dentro de uma `div` específica.

Utilizando o `include` no Controller da página faz com que a inclusão aconteça antes do header...

Como devo fazer para que ela aconteça dentro da minha `div`?

Obrigado!

**Comment by Lesnock** [comment]
Ops... Já consegui! hahaha

Eu estava adicionando a URL BASE sem necessidade.

Desculpem! ^_^

**Comment by Davidsonc** [comment]
@Lesnock poderia mostrar como ficou o bloco de codigo da div com o include ?

**Comment by Lesnock** [comment]
@Davidsonc 
Desculpe, não tenho mais esse código.
Mas o melhor modo de fazer isso é utilizando views parciais.
Segue a documentação:
https://github.com/brunosantoshx/hxphp-docs/blob/master/06-views.md
