### ISSUE TITLE
EXPORT XLS, CSV e PDF

### ISSUE THREAD

**Issue by pazini** [brunosantoshx/hxphp#53]
Amigo...

Tenho uma necessidade e estou com dificuldades de usar dentro do HXPHP.

Preciso que um retorno de um **model::find()** ou **model::find_by_sql()** seja exportado em **XLS, CSV** e **PDF**.

Pode ajudar?! Existe algum Helper que possa usar para me auxiliar nessa empreitada.

Forte abraço!

**Comment by brunosantoshx** [comment]
Olá @pazini, como vai?

O HXPHP não conta com nenhum recurso nativo para tal exportação, porém acredito que você consiga realizar tal procedimento facilmente com uma ferramenta específica.

Exemplo:
https://github.com/elidickinson/php-export-data

Você poderia percorrer o retorno do DB com um foreach e adicionar as linhas no documento através da conversão dos dados para `array` com o `->to_array();` Veja: http://www.phpactiverecord.org/boards/4/topics/758-how-to-get-result-set-as-an-array

Espero ter ajudado.
Abração!
