### ISSUE TITLE
Retorno Banco de Dados tipo Float ou Text

### ISSUE THREAD

**Issue by duducp** [brunosantoshx/hxphp#54]
Boa tarde, estou a utilizar o MYSQL e quando busco os dados no BD com o ActiveRecord não estou conseguindo retorno de dados do tipo Float ou Text no BD para as input. Os valores de VARCHAR são retornados normalmente. Vocês saberiam me dizer como posso retornar esses tipo de dados para uma input?

**Comment by brunosantoshx** [comment]
Olá @duducp, como vai?

Você pode colar aqui o resultado impresso com o uso da função `var_dump($variavel)`?

**Comment by duducp** [comment]
Boa tarde Bruno confira abaixo o que foi retornado...

`object(stdClass)#33 (1) { ["ads"]=> object(Advertising)#71 (6) { ["errors"]=> NULL ["attributes":"ActiveRecord\Model":private]=> array(26) { ["id"]=> int(17) ["title"]=> string(5) "fdgdf" ["description"]=> string(4) "fgdf" ["user_id"]=> int(3) ["date_add"]=> object(ActiveRecord\DateTime)#75 (5) { ["model":"ActiveRecord\DateTime":private]=> *RECURSION* ["attribute_name":"ActiveRecord\DateTime":private]=> string(8) "date_add" ["date"]=> string(26) "2016-06-18 00:00:00.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(17) "America/Sao_Paulo" } ["hour_add"]=> string(8) "04:25:04" ["stock"]=> string(0) "" ["brand"]=> string(0) "" ["color"]=> string(0) "" ["finishing"]=> string(0) "" ["yield"]=> string(0) "" ["dilution"]=> string(0) "" ["manufacturer"]=> string(0) "" ["price"]=> float(43534) ["product_code"]=> string(0) "" ["feature"]=> string(0) "" ["line"]=> string(0) "" ["packing"]=> string(0) "" ["composition"]=> string(0) "" ["shelf_life"]=> string(0) "" ["applications"]=> string(0) "" ["weight"]=> string(0) "" ["usee"]=> string(0) "" ["drying"]=> string(0) "" ["date_att"]=> NULL ["hour_att"]=> NULL } ["__dirty":"ActiveRecord\Model":private]=> array(0) { } ["__readonly":"ActiveRecord\Model":private]=> bool(false) ["__relationships":"ActiveRecord\Model":private]=> array(0) { } ["__new_record":"ActiveRecord\Model":private]=> bool(false) } }`

Como você pode perceber o description está como text no BD e está sendo retornado o valor, a imput não é preenchida com esse valor retornado.

Action:
![screenshot_1](https://cloud.githubusercontent.com/assets/16366240/16509117/2c39444c-3f10-11e6-99db-e18b6804d792.png)

Preenchimento da imput no html:
![screenshot_2](https://cloud.githubusercontent.com/assets/16366240/16509212/dd6a724a-3f10-11e6-80df-35607d1e1a4e.png)

**Comment by brunosantoshx** [comment]
Olá @duducp, como vai?

O seu problema está no HTML.  O atributo `value` não existe para áreas de texto. O correto seria:

```php
<textarea><?php echo $view_dados->description; ?></textarea>
```

**Comment by brunosantoshx** [comment]
Confira: http://www.w3schools.com/tags/tag_textarea.asp
