### ISSUE TITLE
Field 'development' not found in class HXPHP\System\Configs\Config;

### ISSUE THREAD

**Issue by deigonPrates** [brunosantoshx/hxphp#55]
Me deparei com esse problema, não sei o que fazer para resolver. Estou seguindo o passo a passo do tutorial 2. Como corrigir?
<?php
	//Constantes
	$configs = new HXPHP\System\Configs\Config;
	$configs->env->add('development');
        $configs->env->development->baseURI='/sistema/';

**Comment by brunosantoshx** [comment]
Olá @deigonPrates, como vai?

Poderia anexar um print? E também poderia me passar qual é a versão que está utilizando?

**Comment by deigonPrates** [comment]
Tudo ótimo @brunosantoshx e com vc?
[https://i.imgsafe.org/1bcaee2413.png](url)

PHP Version 5.6.20, Apache 2.0 Handler.

**Comment by brunosantoshx** [comment]
Tudo ótimo!

Esse erro só ocorre no IDE? Se sim, não é um erro, amigo. Quando você usa o método `add(...)` está injetando o ambiente e, portanto, somente após isto será possível acessar esta propriedade e seus respectivos conteúdos.

**Comment by deigonPrates** [comment]
Tava usando o Netbeans e o PHPStorm, ambos estavam apresentando o problema mudei para o Sublime tudo funcionando perfeitamente.

**Comment by duducp** [comment]
Na verdade o sublime é voltado somente para frontend (sem suporte ao PHP nativamente) por isso ela não retornou o erro. Creio que se o PHPStorm e o Netbeans estão retornando erro acho que você deve verificar e não deixa-lo.
