### ISSUE TITLE
Retorno da Pagina necessita Reload.

### ISSUE THREAD

**Issue by pazini** [brunosantoshx/hxphp#56]
Bruno

Quando por qualquer motivo preciso voltar a pagina (Alt + Seta Esquerda) ou mesmo direto no Navegador, ele pede que dê um refresh na página. Meu usuário esta me perturbando como se fosse erro!

Como faço para que quando haja um voltar a pagina nao solicite isso ou que forçe o refresh automaticamente?!

Existe como criar um botão "VOLTAR" na aplicação que faça um refresh da pagina anterior?!

Abs.

**Comment by brunosantoshx** [comment]
Olá @pazini, como vai?

O que acontece é que o seu cliente deve estar tentando voltar para uma página anterior após um formulário ser enviado com o método POST. Acredito que a melhor solução seja redirecionar o usuário para a página que ele insiste em voltar após a ação ser executada. Ou você pode adicionar um link voltar (somente o fato de ser um link já muda totalmente o cenário em comparação com o botão voltar do navegador).

Espero ter ajudado!
Abs

**Comment by Davidsonc** [comment]
@pazini gostaria de saber qual solução você deu para essa situação do alt+seta para esquerda, e que solução o @brunosantoshx daria, diferente do link, pois é complicado remover vícios de usuários como é o caso do pressionamento dessas teclas.
