### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by brunomaarts** [brunosantoshx/hxphp#58]
![capturar](https://cloud.githubusercontent.com/assets/20291077/16572153/c3264476-423b-11e6-9772-74a4e4d06d60.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/20291077/16572154/c328bcd8-423b-11e6-8d13-09f7208ff0c9.PNG)

Olá Bruno, to amando a sua série é realmente muito boa. Estava tudo correndo muito bem, porém estava quase terminando a sua 8ª aula e me deparo com um erro horrível na hora de verificar o login, não consigo arrumar isso de jeito nenhum. Se for um erro grotesco por favor me perdoe.

**Comment by brunomaarts** [comment]
Valeu Brunão, já consegui arrumar. Errei na escrita do meu banco de dados

**Comment by brunosantoshx** [comment]
Show xará!
