### ISSUE TITLE
Como setar uma variável do tipo $_POST?

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#59]
Eu sei que para recuperar valores do POST no HXPHP basta utilizar:
`$this->request->post()`

Mas, como eu poderia fazer para "setar" um valor no POST?
Algo assim (só como exemplo):
   `$this->request->post('name') = 'Caio Lesnock';`

Assim como fazemos no PHP original:
   `$_POST['name'] = 'Caio Lesnock';`

Há alguma maneira de fazer isso no HXPHP?
Obrigado!

**Comment by brunosantoshx** [comment]
Olá @Lesnock, como vai? 

Você pode fazer o seguinte:

```php
$post = $this->request->post();
$post['name']  = 'Caio Lesnock';

var_dump($post);
```

**Comment by Lesnock** [comment]
Bruno, acho que você não entendeu muito bem a minha dúvida.
Não quero capturar o $_POST e armazená-lo em uma variável. Quero de fato "setar" um índice no $_POST. Normalmente isso se faz através dos formulários, mas quero setá-lo manualmente.
Para ser mais claro, vou explicar a situação:

Estou criando um sistema empresarial onde as pessoas podem inserir dados em tabelas.
Então o usuário preenche um formulário e através do atributo `action` deste formulário ele é redirecionado para uma action do Controller chamada `addAction`. 
Nesta action é feito a validação do formulário enviado. E após isso, o usuário é automaticamente jogado de volta para a URL anterior. 
Nesta "volta" o usuário recebe um **alert** recebido através do `$_SESSION['message']`.

Acontece que, se as validações da minha `addAction` resultarem uma mensagem de erro, o registro não será feito. E aí é que está a chave do problema: caso ocorra algum erro, não quero que o usuário receba a mensagem de erro e tenha que escrever todo o formulário novamente. Então coloquei o `$this->request->post()` dentro dos `values` de cada `input`. Mas como vou recuperar o POST se a página foi atualizada? Por isso queria setá-los manualmente. Assim eu poderia enviar um `$_SESSION['post']` que contivesse todos os campos do formulário.
Espero que não tenha ficado muito confuso...

Consegue me ajudar com isto? 
Muito obrigado!

**Comment by Davidsonc** [comment]
@Lesnock qual solução você adotou para resolver esse problema ?

**Comment by Lesnock** [comment]
@Davidsonc Na vdd eu não obtive uma solução concreta pra esse problema.
Não há maneira de setar um post manualmente.
Somente atribuindo o valor do post para outra variável.
