### ISSUE TITLE
HXPHP + PostgreSQL

### ISSUE THREAD

**Issue by pcampello** [brunosantoshx/hxphp#6]
Olá Bruno,

primeiramente parabéns pelo framework.

Como uma sugestão de melhoria poderia possibilitar  o uso de outros bancos como postgreSQL por exemplo.

Não sei se eu fiz da maneira correta mas alterei o seguinte:
Adicionei um atributo chamado driver na classe database;
No arquivo /src/HXPHP/System/App.php substitui o 'mysql' por "$this->configs->database->driver."

**Comment by brunosantoshx** [comment]
Olá, como vai?

Muito obrigado pelo feedback! Fico feliz que esteja gostando do HXPHP.

Simplesmente perfeito! O que me diz de subir esta alteração em um PR?

**Comment by pcampello** [comment]
Bruno, desculpe a ignorância, mas o que seria um PR?

Tem alguma documentação onde eu consiga aprender como "subir a alteração em um PR"?

**Comment by carusogabriel** [comment]
Olá @pcampello 

Um PR seria um `Pull Request`. Aqui no GitHub você pode dar `Fork` em um projeto, e propor um PR para o administrador do repositório!

Procure na internet por `Pull Request` no GitHub!

Espero ter ajudado!

**Comment by pcampello** [comment]
Opa, valeu Gabriel, ajudou sim.

Bruno, irei fazer a PR.

**Comment by brunosantoshx** [comment]
Que massa! É incrível ver a comunidade iniciando e a galera se ajudando!

Valeu pela força, Gabriel!

Já recebi o PR, vou olhar agora mesmo :D
