### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by nathanramorim** [brunosantoshx/hxphp#62]
@brunosantoshx, eu fiz a instalação do hxphp porém não estou conseguindo acessar a primeira pagina conforme o video, https://www.youtube.com/watch?v=C4dvlQPJalU (em 7:50 minutos)

Fatal error: Class 'HXPHP\System\Services\StartSession\StartSession' not found in /var/www/html/clientes/plurall/index.php on line 31

O .htaccess está assim 
```
Options +FollowSymLinks
Options -Indexes

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /plurall/
	RewriteRule ^index\.php$ - [L]
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule . /plurall/index.php [L]
</IfModule>

<Files ~ "^\.(htaccess|htpasswd)$">
  deny from all
</Files>

<IfModule mod_deflate.c>
  <FilesMatch "\.(js|css|jpg|png|gif|ico|php|html|htm)$">
    <ifModule mod_filter.c>
      SetOutputFilter DEFLATE
      AddOutputFilterByType DEFLATE text/css text/javascript application/x-javascript text/html text/plain text/xml image/x-icon
    </IfModule>
  </FilesMatch>
</IfModule>
```
o módulo rewrite do apache está ativo.

tem alguma ideia do que pode ser ?  
Obrigado.

**Comment by skay1994** [comment]
como esta o arquivo index.php onde é informado o erro? aparentemente a classe ta declarada nessa linha porem nao existe o arquivo. /var/www/html/clientes/plurall/index.php on line 31

**Comment by nathanramorim** [comment]
@skay1994 
O index.php está assim:
```
<?php
	ob_start();

	ini_set('display_errors', 1);
	set_time_limit(0);

	date_default_timezone_set('America/Sao_Paulo');
	setlocale(LC_ALL, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');

	define('DS', DIRECTORY_SEPARATOR);
	define('ROOT_PATH', dirname(__FILE__) . DS);
	define('APP_PATH', 'app' . DS);
	define('TEMPLATES_PATH', ROOT_PATH . 'templates' . DS);

	define('HXPHP_VERSION', '2.5.8');

	/**
	 * Verifica se o autoload do Composer está configurado
	 */
	$composer_autoload = 'vendor' . DS . 'autoload.php';

	if ( ! file_exists($composer_autoload))
		die('Execute o comando: composer install');

	if (version_compare(PHP_VERSION, '5.4.0', '<'))
		die('Atualize seu PHP para a vers&atilde;o: 5.4.0 ou superior.');

	require_once($composer_autoload);

	//Start da sessão
	$session = new HXPHP\System\Services\StartSession\StartSession;
	
	$session->sec_session_start();

	//Inicio da aplicação
	$app = new HXPHP\System\App(require_once APP_PATH . 'config.php');
	$app->ActiveRecord();
	$app->run();
```

**Comment by skay1994** [comment]
olha comparando o seu arquivo index com o que ta no repositório, existem diferenças na área do erro, substitui o seu pelo original e testa: [hxphp/index.php](https://github.com/brunosantoshx/hxphp/blob/master/index.php)

**Comment by brunosantoshx** [comment]
Olá @nathanramorim, como vai?

Você verificou se a classe mencionada no erro realmente existe no diretório especificado? Isto é, existe a pasta: `src/HXPHP/System/Services/StartSession/`? Se sim, o arquivo também existe? 

Este é o código que deve constar:
https://github.com/brunosantoshx/hxphp/blob/master/src/HXPHP/System/Services/StartSession/StartSession.php

E também o seu arquivo `index.php` foi alterado. O método é estático. 

Forte abraço e sucesso sempre!

**Comment by nathanramorim** [comment]
fiz a alteração, deu certo parece, muito obrigado @skay1994 e @brunosantoshx  só que não, ainda não encontra a página conforme mostra no vídeo.

veja oque ocorre:
![captura de tela_2016-08-01_21-18-51](https://cloud.githubusercontent.com/assets/8780740/17312952/ba225e98-582d-11e6-9be3-002e4ee7a3f6.png)

**Comment by brunosantoshx** [comment]
Olá @nathanramorim, como vai?

Provavelmente as configurações de BASE URI estão incorretas. Verifique o arquivo `app/config.php` e o `.htaccess`. 

Forte abraço e sucesso sempre!
