### ISSUE TITLE
Uma validaçao de hash de senha mais facil

### ISSUE THREAD

**Issue by skay1994** [brunosantoshx/hxphp#64]
Seria possível uma validação de senha mais simples, para ser feito no estilo `\HXPHP\System\Tools::verifyHashHX($user_id,$passwordForm,$salt)` ??

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai?

Infelizmente não. O `Tools` é um objeto auxiliar que fornece alguns recursos de uso recorrente. Qualquer validação ou manipulação de dados **deve** ser realizada na camada dos `models`, portanto a criação deste método violaria o padrão MVC.

Espero ter ajudado.
Forte abraço e sucesso sempre!
