### ISSUE TITLE
Modulo personalizado.

### ISSUE THREAD

**Issue by skay1994** [brunosantoshx/hxphp#65]
@brunosantoshx  Ei cara, fiz um modulo personalizado para usar o login do Facebook no framework, e como não existe um local para compartilhar fiz esse issue para mostrar a comunidade!! E aproveitando, uma duvida, seria possível um local especifico para compartilhar esses modulos da comunidade?

https://github.com/skay1994/Facebook-Login---HXPHP

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai?

Poxa, que bacana! Como você foi o primeiro com esta ideia até então não tinha pensado no assunto. O que acha da ideia de um repositório `hxphp-modules` ao qual você poderia realizar o fork e upar seu módulo?

Também upei um módulo um tempo atrás:
https://github.com/HXPHP/hxphp-correios

Curti bastante a proposta do seu módulo e acredito que vai ser bem útil para toda a comunidade. Uma dica é melhorar a documentação adicionando syntaxhighlighter para destacar as marcações do PHP e também adicionando um exemplo completo. 

Enfim, fico no aguardo dos seus comentários.
Forte abraço e sucesso sempre!

**Comment by skay1994** [comment]
Olá @brunosantoshx, fiz as mudanças sugeridas, peço que analise e passe um feedback, pois é a primeira documentação que faço.

Quanto aos módulos, seria ótimo um repositório, e para mostrar o que o framework possibilita, acredito que montar uma comunidade no estilo de fórum facilitaria a organização dos módulos e também criaria uma comunidade para discussão em assuntos relacionados a cada modulo.

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai?

Está ficando cada vez melhor. Parabéns! Espero que seu trabalho possa inspirar outras pessoas e realmente construirmos uma comunidade como sugeriu.

Vou pensar a respeito de criar um fórum e uma ferramenta que facilite a instalação dos módulos também. 

Pelo que vi, seguem algumas observações:
- O módulo não é compatível com a versão atual do HXPHP? Se sim, altere para a versão atual e coloque o link de download da release específica. Atualmente você está apontando para o branch master com a versão mais recente e isto pode trazer alguns problemas de compatibilidade;
- Sobre o uso do Facebook SDK: Acredito que seria mais interessante você colocar o comando do `composer` para que os arquivos sejam importados no projeto da forma correta;
- Na parte de instalação dá pra colocar os requisitos como passos: 1) git clone hxphp (na versão compatível); 2) composer require facebook/php-sdk-v4; 3) Extração dos arquivos; 4) Registro do módulo; 5) Configuração do app/config.php, e; 6) Exemplo de uso;
- Ajustar indentação de código e se atentar para padrões de código (chaves de métodos em uma linha específica; espaços antes e depois dos parênteses; sintaxe simplificada para arrays, e; etc);
- Penso que na injeção do módulo ao invés de você inserir parâmetro por parâmetro você pode injetar o módulo de configuração e dentro do módulo resgatar cada valor individualmente. Isto seria para diminuir a quantidade de código para o programador final;
- Acredito que a seção Outras informações deva fazer parte do `Exemplo de uso`, isto é, um exemplo com passo a passo.

Cara, o módulo tem uma proposta show de bola e pretendo gravar utilizando ele em breve porque sem dúvidas vai ser um conteúdo show de bola pra galera. Muito obrigado por compartilhar!

Espero ter ajudado.
Forte abraço e sucesso sempre!

**Comment by brunosantoshx** [comment]
Outra dica: Utilize o `git tag` para criar as releases. É importante para organizar o repositório e informar as novidades de cada versão.

**Comment by skay1994** [comment]
@brunosantoshx fiz as mudanças passadas, so não consegui usar o `git tag`, na versão local ele mostra a versão porem no repositório não aparece, nao consegui entender como fazer a questão de injeção do modulo, pode explicar por favor?

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai?

Está ficando cada vez melhor, amigo! Parabéns!

Sobre suas dúvidas:
+ Você precisa upar as tags usando o comando: `git push --tags` e depois criar a release no Github;
+ A injeção do módulo seria isto:

```php
$this->load('Modules\Facelogin',
            $this->configs->facelogin->appid,
            $this->configs->facelogin->appsecret,
            $this->configs->facelogin->redirect_url,
            $this->configs->facelogin->fieldlogin,
            $this->configs->facelogin->permslogin
);
```

se tornar isto:

```php
$this->load('Modules\Facelogin', $this->configs->facelogin);
```

E no construtor do módulo você colocaria uma validação de instância para impedir que outros objetos sejam passados e utilizaria os parâmetros conforme a aplicação necessita. Claro que é só uma sugestão.

**Comment by skay1994** [comment]
Atualizado com as mudanças sugeridas, sugestões são sempre bem, principalmente para mim que estou agora começando a publicar meus códigos em PHP!!

**Comment by brunosantoshx** [comment]
Ficou excelente!

Você tem alguma ideia de alguma forma bacana de divulgar o módulo? Estava pensando em criar um repositório com apenas um `README` com os nomes, descrições e links dos módulos desenvolvidos, mas não sei se é o suficiente pq queria realmente fazer mais. O que acha desta ideia?

Fico no aguardo.

Abs

**Comment by skay1994** [comment]
Já é um ótimo começo, seria um repositório de referencia e assim, todos os módulos também teriam um link para essa pagina. Cria o repositório e um modelo de como vai ser apresentado os módulos para manter um padrão

**Comment by brunosantoshx** [comment]
Maravilha @skay1994! Vou providenciar
