### ISSUE TITLE
Certificado invalido

### ISSUE THREAD

**Issue by skay1994** [brunosantoshx/hxphp#66]
Ei @brunosantoshx fui acessar hj o site oficial do HXPHP e recebi esse erro de certificado.

![image](https://cloud.githubusercontent.com/assets/5720296/17366172/359a1092-5960-11e6-9c74-7db35ff06516.png)

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai?

Você acessou a partir de um link ou digitou o endereço do site? Se foi via link, pode me dizer onde este link está?

É que o certificado SSL expirou e agora o site não pode ser mais acessado pelo https e sim somente via http. Já alterei em vários lugares, mas devo ter deixado passar algum.

Fico no aguardo.
Forte abraço e sucesso sempre!

**Comment by skay1994** [comment]
fiz o acesso atravez do readme aqui mesmo do hxphp, o link para a documentação retorna isso, agora sem o /documentacao/ funciona normal sem esse erro.

**Comment by brunosantoshx** [comment]
Entendi! Já corrigi o problema. Valeu pelo feedback!
