### ISSUE TITLE
Redirecionamento de página dando erro!

### ISSUE THREAD

**Issue by junio-gon** [brunosantoshx/hxphp#67]
Boa noite! Usando o HXPHP só a primeira index (sucessful) da certo, as demais retorna o 404 padrão. Inclusive para o teste "cadastro"! Não encontro o erro!

**Comment by skay1994** [comment]
vc criou o controler da pagina cadastro?

**Comment by junio-gon** [comment]
skay1994, revisei a configuração (video #2) e encontrei o erro, havia esquecido de alterar o arquivo .htaccess, agora funcionou! Obrigado pela ajuda!
