### ISSUE TITLE
Setando $_POST manualmente.

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#68]
Olá,
Percebi que ao setar um índice para a variável global $_POST, ao tentar recuperá-la com 
`$this->request->post` ele sempre retorna nulo.

Por exemplo, se eu executar esse código:
```
$_POST['name'] = 'Caio Lesnock';
var_dump($this->request->post());
```

O resultado será um valor nulo.

Há algo que eu possa fazer em relação à isso?

Muito obrigado!

**Comment by skay1994** [comment]
posso estar falando besteira, mas nao seria assim que se passa informações para a $_POST, isso vai como cabeçalho para a proxima pagina, por isso formularios e ajax conseguem definir

**Comment by Lesnock** [comment]
Na verdade, pelo que eu sei, é totalmente possível passar informações para o $_POST desta maneira. Tanto é que eu consigo acessá-la normalmente da seguinte forma:

`var_dump($_POST);`

No entanto, quando utilizo a função `$this->request->post()` não funciona, apenas retorna um valor nulo.

**Comment by skay1994** [comment]
isso mesmo, no php puro é possivel sim, no framework é como falei é passado pelo header por isso que nao consegue via a função do proprio framework, tenta usar via ajax

**Comment by brunosantoshx** [comment]
Olá @Lesnock, como vai?

O que ocorre é que os valores retornados pelo método `post()` são obtidos através da constante `INPUT_POST`, isto é, alterar a superglobal `$_POST` não influencia neste método do framework. Foi como o @skay1994 disse, ou seja, a informação é recebida diretamente via protocolo HTTP. 

Se precisa adicionar alguma informação ao POST é recomendado utilizar AJAX ou cURL para enviar as outras informações via protocolo HTTP. Ou você pode trabalhar com GET e adicionar as informações que deseja para montar uma nova URL com estes parâmetros e redirecionar o usuário. 

Forte abraço e sucesso sempre!
