### ISSUE TITLE
undefined constant TEMPLATES_PATH

### ISSUE THREAD

**Issue by skay1994** [brunosantoshx/hxphp#69]
Toda vez que tento usar o template aparece esse erro, ja olhei e o arquivo alert.html e alert-list.html estao na pasta porem, nao consigo achar a constante `TEMPLATES_PATH`, vi pelo historico de [commits](https://github.com/brunosantoshx/hxphp/pull/51/commits/5dafafdd2ade8dd7505654d3145d0fad69093f3c) que tem o comando para criar ela, porem percebi que o meu arquivo nao tinha o comando, entao coloquei manualmente e não resolveu o problema, agora não diz q a constante é indefinida, mais ainda nao funciona os alertas.  Se passar as informações sem o alerta funciona normalmente.

Obs: estou usando seguinte forma
```php
               $alerta = array('danger',
                    'Ops... Ocorreu um erro no login, veja abaixo:',
                    $login->erros
                );

                $this->load('Helpers\Alert', $alerta);
```
 
![image](https://cloud.githubusercontent.com/assets/5720296/17627121/751db75a-6086-11e6-8d42-35c2643f8b79.png)

![image](https://cloud.githubusercontent.com/assets/5720296/17627425/90fc08e0-6087-11e6-8f03-aca3f90adc61.png)

**Comment by brunosantoshx** [comment]
Olá @skay1994, como vai?

É que esta constante foi adicionada recentemente no `index.php` que fica na raiz da aplicação. Confira:

https://github.com/brunosantoshx/hxphp/blob/master/index.php


É só atualizar este arquivo que o problema será solucionado.

Abraço e sucesso sempre!
