### ISSUE TITLE
Dúvida sobre o Alert Helper

### ISSUE THREAD

**Issue by Lesnock** [brunosantoshx/hxphp#70]
Eu comecei a estudar PHP OO há pouco tempo, então ainda não entendo totalmente como as coisas funcionam. Por isso estava lendo o código do HXPHP para melhorar um pouco minhas noções no PHPOO. No entanto me deparei com uma questão sobre funcionamento do Alert Helper.

Eu percebi que quando a mensagem é renderizada, ela é enviada para a sessão 'message'. 
Apesar disso, depois de carregar o Helper, posso exibi-lo, tanto no controller quanto na view simplesmente com um `echo $this->alert;`.

Gostaria de saber como isso é possível? 
De onde está vindo esse `alert`? E como ele consegue exibir a `div` mesmo sem recuperá-la da `session` ?? 
Ao quê se refere exatamente o `$this` nesse caso, ao Controller ou à classe Alert? 

Alguém pode me ajudar? 
Muito obrigado!

**Comment by Lesnock** [comment]
Pesquisei um pouco e descobri que o responsável por isso é a função `__toString`, da classe` Alert`, certo?

Mas ainda resta uma dúvida. Como é possível exibir o `alert `na view?

**Comment by skay1994** [comment]
Eu tb não sei como é feito isso, porem se vc der um `var_dump($configs)` na variavel `$configs` depois de ter iniciado o alerta, aparece um objeto com os alertas que vc criou, acredito que seja incluído todo o conteúdo do alerta nessa variável e como ela é global no sistema seja possível exibir ela tem qualquer lugar

**Comment by brunosantoshx** [comment]
Olá @Lesnock, como vai?

Poxa cara, que legal! Você é a primeira pessoa que utilizou o HXPHP para este propósito (ao menos que postou por aqui :)) e curti demais a sua dúvida.  

Agora... respondendo:
- O `$this` presente na `view` é referente ao objeto `View`. Você pode debugar com `print_r($this)`, por exemplo, para obter mais detalhes sobre sua estrutura;
- O método `load()` do `Controller` **injeta a dependência** no objeto `View`. Como o método pertence ao objeto `Controller` realmente existe a falsa impressão de que a injeção ocorre nele próprio, mas isto só foi feito para simplificar a chamada dos métodos. Se você ainda não conhece o conceito de injeção de dependências é fundamental que adicione à sua lista de estudos;
- O `AlertHelper` renderiza a mensagem e armazena o HTML do template em uma `session`; 
- Agora uma pergunta: Por que `$this->alert` funciona tanto no controller como na view se são objetos diferentes? A resposta: **método mágico** `__get()`. Este método mágico possibilita que ao buscar por uma propriedade (dependência) no objeto `Controller` eu também verifique se  existe no objeto `View`;
- Existe um método no AlertHelper responsável por buscar o conteúdo da `session` e imprimir;
- E sobre o esquema de `echo $this->alert;` é o que você já postou: **método mágico** `__toString()`.

Espero ter ajudado e fico na torcida que continue firme e forte com os estudos do PHPOO.

Forte abraço e sucesso sempre!
