### ISSUE TITLE
Fatal Error no Linux

### ISSUE THREAD

**Issue by alanweing** [brunosantoshx/hxphp#71]
Olá, Bruno! Tudo bem?

Consegui rodar o teu framework, sem problemas, no Mac e no Windows. Porém, quando tento fazer o mesmo, seguindo os mesmos passos, no Linux, recebo o erro:

`Fatal error: Uncaught exception 'Exception' with message 'Parametro/Modulo 'baseURI' nao encontrado. Verifique se o ambiente definido esta configurado e os modulo utilizados registrados.' in /var/www/html/sistema/src/HXPHP/System/Configs/Config.php:29 Stack trace: #0 /var/www/html/sistema/src/HXPHP/System/App.php(33): HXPHP\System\Configs\Config->__get('baseURI') #1 /var/www/html/sistema/index.php(34): HXPHP\System\App->__construct(Object(HXPHP\System\Configs\Config)) #2 {main} thrown in /var/www/html/sistema/src/HXPHP/System/Configs/Config.php on line 29`

Se puder dar uma ajudinha, eu agradeço.
Grande abraço!

**Comment by skay1994** [comment]
eu tive um problema parecido, porem com a configuração do banco de dados, resolvi alterando o arquivo da pasta Environments referente ao ambiente, no meu caso o ambiente de produção precisei tirar o comando
```php
ini_set('display_errors', );
``` 
e apos isso funcionou normalmente

**Comment by brunosantoshx** [comment]
Olá @alanweing, tudo sim e contigo?

Uma das contribuições recentes acabou resultando em um bug quando o ambiente de produção era selecionado e ocorria justamente nas configurações do framework. Subi um commit com a correção e acredito que possa ser este o problema. Isto porque o ambiente de desenvolvimento só é setado desde que a URL do servidor local esteja listada nos `servers`. É apenas uma suspeita, portanto fico no aguardo dos seus comentários.

Forte abraço e sucesso sempre!

PS: @skay1994 te mandei um convite para participar da organização HXPHP. Decidi tomar um caminho diferente: Todo repositório de módulo para HXPHP será movido para a organização e assim a sua autoria será mantida, você poderá atualizar sempre que necessário e tudo ficará centralizado. Fico no aguardo. Abs
