### ISSUE TITLE
Composer (comando não encontrado)

### ISSUE THREAD

**Issue by D4rkw0lv3s** [brunosantoshx/hxphp#72]
Quando eu escrevi o comando composer install, a seguir dizia comando nao encontrado como assim?

Se me poder mandar a resposta por email agradecia: tresrockeiros@hotmail.com

**Comment by skay1994** [comment]
vc instalou o composer em sua maquina, o comando depende dele instalado, faça o download nesse site [https://getcomposer.org/download/](https://getcomposer.org/download/)

**Comment by brunosantoshx** [comment]
Olá @D4rkw0lv3s, como vai? 

Foi o que o @skay1994 te disse acima. Você precisa instalar o Composer e, infelizmente, em ambientes Windows você terá que fazer algumas adaptações. Meu conselho é que migre o quanto antes para sistemas UNIX para evitar dor de cabeça.

Forte abraço e sucesso sempre!
