### ISSUE TITLE
HXPHP - Ops! Nada encontrado! .../usuarios/listar/

### ISSUE THREAD

**Issue by coutofx** [brunosantoshx/hxphp#73]
Já revisei tudo e ainda não estou conseguindo acessar nada além da página inicial(uhu). Quando tento acessar por exemplo 127.0.0.1:8080/site/usuarios/listar/  Apresenta a mensagem: Ops! Nada encontrado!

Cheguei a testar numa versão antiga do HXPHP e funcionou, mas na atual não.

Uso: Linux, porta apache 8080, HXPHP Versão 2.5.8, e já testei mod_rewrite if (in_array("mod_rewrite",apache_get_modules())) print "Ok";

**Comment by skay1994** [comment]
se chega a essa tela não é problema de mod_rewrite, veja os arquivos, se estão bem escritos a função que deseja usar, veja se declaro o controller de forma correta e a action tb

**Comment by coutofx** [comment]
Vou refazer novamente, mas mesmo uma saída como o código não reconhece.

<?php
class UsuariosController extends \HXPHP\System\Controller
{
	public function listarAction()
	{
		print 'Testando ...'; exit;
	}
}

**Comment by coutofx** [comment]
skay1994, está funcionando agora, mas sem explicações até o momento pois não alterei nada. Acredito que o problema tem relação com minha instalação do PHP, algo tipo opcache nas configurações.

Obrigado!

**Comment by brunosantoshx** [comment]
Olá @coutofx, como vai?

Configurar um servidor local em sistemas Linux é sempre problemático. Existe a questão das permissões e também a edição dos arquivos de configuração do Apache e do PHP. 

Se lembrar da solução é importante postar aqui para ajudar outros que possam enfrentar a mesma dificuldade. 

Forte abraço e sucesso sempre!

**Comment by coutofx** [comment]
O problema é que mesmo modificando conteúdo dos scripts as paginas não atualizavam no navegador, repetindo assim um erro já corrigido, então pesquisando solucionei esta questão desabilitando o Op Cache do PHP(php.ini) tornando-os igual a zero:
opcache.enable = 0
opcache.enable_cli = 0
