### ISSUE TITLE
HXPHP não carrega ambiente de desenvolvimento

### ISSUE THREAD

**Issue by coutofx** [brunosantoshx/hxphp#74]
Prezados, estou com uma dificuldade, não tenho certeza, mas está parecendo que o HXPHP não acata as informações que estou fixando em app/config.php para o ambiente de desenvolvimento. Mesmo configurando os dados de acesso ao DB, apresenta erro de conexão por falta de senha.

Para alterar o a baseURL estou tendo que informar diretamente em src../AbstractEnvironment.php

Já as configurações em EnvironmentDevelopment.php como servidor não surte nenhum efeito.

Se alguém tiver uma dica, agradeço!

Obrigado a todos!

**Comment by brunosantoshx** [comment]
Olá @coutofx, como vai?

Pode me passar qual é o link que está utilizando para acessar o sistema no ambiente local? Ex: 127.0.0.1:8080/hxphp e etc.

**Comment by coutofx** [comment]
Fala Bruno! 
O link é: http://127.0.1.1:8080/site/ e o diretório fica em: /home/andre/lamp/apache2/htdocs/site

Só abre a pagina inicial do framework e mesmo para isto tenho que fazer os seguintes procedimentos:

Alterar o **.htaccess** informando minha base(site):

> <IfModule mod_rewrite.c>
> 	RewriteEngine On
> 	RewriteBase /site/
> 	RewriteRule ^index\.php$ - [L]
> 	RewriteCond %{REQUEST_FILENAME} !-f
> 	RewriteCond %{REQUEST_FILENAME} !-d
> 	RewriteRule . /site/index.php [L]
> </IfModule>

**Teste 1 -** Apresenta a mensagem [**Uhull! Você instalou e configurou o HXPHP Framework com sucesso!**], mas sem qualquer carregamento de css ou imagem do HXPHP.

Depois alterar em **/site/app/cofnig.php** informando minha baseURI(site)

> $configs->env->development->baseURI = '/site/';

**Teste 2 -** Até este ponto não apresenta nada, nem mesmo a imagem /public/img/hxphp-logo.png, somente a informação: [**Uhull! Você instalou e configurou o HXPHP Framework com sucesso!**].

A tela de sucesso do framework HXPHP só aparece normalmente quando faço a **alteração** no arquivo **/site/src/HXPHP/System/Configs/AbstractEnvironment.php** informando minha baseURI(site):

> $configs->env->development->baseURI = '/site/';

Por final, toda alteração que eu em  **/site/src/HXPHP/System/Configs/Environments/EnvironmentDevelopment.php** não surte o minimo efeito na aplicação e nem acesso ao banco de dados.

Posso até deixar assim como abaixo que nada acontece:

> $this->servers = [
>     'localhost BLA, BLA,BLA',
>     '127.0.0.1kjdfkjhsdkjfs'
> ];

E nas configurações de acesso a banco de dados também não reconhece:

> $configs->env->development->database->setConnectionData([
> 	'driver' => 'mysql',
> 	'host' => '127.0.0.1:3306',
> 	'user' => 'root',
> 	'password' => '102030',
> 	'dbname' => 'hxphp', // Criei o db com este nome mesmo
> 	'charset' => 'utf8'
> ]);

**Brunno, fico grato pela ajuda! Obrigado amigo**

**Comment by brunosantoshx** [comment]
Fala @coutofx, como vai?

Acredito que o problema seja a adição da porta 8080 no hostname. O ambiente é definido mediante a existência do hostname na propriedade `servers`do `/src/HXPHP/System/Configs/Environments/EnvironmentDevelopment.php`, isto é, se você alterar para o código abaixo é provável que o problema seja solucionado:

```php
$this->servers = [
'localhost',
'127.0.0.1:8080'
];
```

Acredito que neste momento como o HXPHP não encontra seu hostname na lista ele está definindo o ambiente de produção como padrão, portanto alterando o ambiente das configs, no cenário atual, para `production` também deveria resolver o problema. Mas, não é a solução recomendada. Portanto, tente primeiramente a solução anterior apresentada.

Forte abraço e sucesso sempre!
