### ISSUE TITLE
Envio de Email

### ISSUE THREAD

**Issue by Ermim** [brunosantoshx/hxphp#75]
Olá, tudo bem?
Estou com problemas no **envio de email**(dá mensagem de sucesso, mas não envia), gostaria de saber onde posso colocar as configurações do meu servidor de email.

É necessário usar PHPmailer e se usar posso adicionar um require_once no controller?

Obrigado!

Aula #13 - validando permissão de acesso.

**Comment by brunosantoshx** [comment]
Olá @Ermim, como vai?

O ideal mesmo é utilizar a classe PHPMailer para poder autenticar com SMTP e disparar os e-mails sem problemas. Mas, para instalar no HXPHP você só precisa incluir a dependência através do Composer e mais nada! Após instalar a dependência é só instanciar e substituir o atual serviço de e-mail no seu código.

Forte abraço e sucesso sempre!
