### ISSUE TITLE
Múltiplos Menus

### ISSUE THREAD

**Issue by rodrigoalbinoh** [brunosantoshx/hxphp#76]
Boa tarde, Bruno! Tudo bem?

Bom, cheguei a um empasse no desenvolvimento do meu site com o HXPHP quanto a múltiplos menus.
Eu gostaria de criar mais de um menu para o meu ambiente, por exemplo, uma sidebar diferente do navbar, mas não encontrei configurações de Menu para tal feito. Inclusive, eu gostaria de criar um dropdown no menu com o nome do meu usuário, porém, estive com dificuldades para passar o nome para o menu. Como devo proceder nesses casos?

**Comment by brunosantoshx** [comment]
Olá @rodrigoalbinoh, como vai?

Atualmente o HXPHP não possui suporte para a exibição de múltiplos menus. Portanto, pode ser uma nova funcionalidade para ser adicionada ao Menu Helper. Por enquanto, a única solução é criar views parciais com menus para cada role; passar a role do usuário como variável para view, e; mediante a condicional exibir o respectivo menu (incluir a view parcial correspondente).

Quanto ao dropdown com o nome do usuário será necessário adaptar as configurações de classe do Menu Helper. Você criará a estrutura com o nome do usuário e etc na própria view e utilizará o Menu Helper apenas para gerar a ul com o dropdown menu.

Espero ter ajudado.
Forte abraço e sucesso sempre!

PS: Vou estudar melhor estas opções e pretendo adicionar estes recursos ao HXPHP

**Comment by dinhodvp** [comment]
Bruno, espero que esteja bem.

Curto muito seus vídeos e vem contribuindo muito para o meu crescimento. Tenho anos de experiência, fiz tudo exatamente como nos vídeos, mas esses dois problemas não me deixam:

1 - Fatal error: Uncaught ActiveRecord\DatabaseException: PDOException: could not find driver in D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php:260 Stack trace: #0 D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(260): PDO->__construct('mysql:host=loca...', 'root', '', Array) #1 D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php(122): ActiveRecord\Connection->__construct(Object(stdClass)) #2 D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\ConnectionManager.php(33): ActiveRecord\Connection::instance('mysql://root:@l...') #3 D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(114): ActiveRecord\ConnectionManager::get_connection('development') #4 D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(90): ActiveRecord\Table->reestablish_connection(false) #5 D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Table.php(71): ActiveRe in D:\xampp\htdocs\_sistema\vendor\php-activerecord\php-activerecord\lib\Connection.php on line 262

2 - Notice: Undefined property: HXPHP\System\View::$alert in D:\xampp\htdocs\_sistema\app\views\cadastro\index.phtml on line 11

com esta linha resolve:<?php echo (isset($this->alert) ? $this->alert : ''); ?>
Porém, desde o início da inserção da variável no echo, nunca e ficou como no seu quinto vídeo da série. Preciso de ajuda, pois gostei muito da série. Abraços!

**Comment by gilglecio** [comment]
@dinhodvp já conseguiu resolver o problema?

**Comment by brunosantoshx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Múltiplos menus](https://trello.com/c/c2bhUnRx/127-multiplos-menus)

**Comment by MarckVinny** [comment]
Como faço para acessar esse arquivo "multiplos menus"??? quando eu clico diz que deve estar num quadro particular.
PS. nunca usei o Trello.

**Comment by MarckVinny** [comment]
> ![](https://camo.githubusercontent.com/193766a3b9959c5f4ed5cd8cf3251d015e839d51/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Múltiplos menus](https://trello.com/c/c2bhUnRx/127-multiplos-menus)

Como faço para acessar esse arquivo "multiplos menus"??? quando eu clico diz que deve estar num quadro particular.
PS. nunca usei o Trello.
