### ISSUE TITLE
Anular footer em view

### ISSUE THREAD

**Issue by majully** [brunosantoshx/hxphp#77]
Olá Bruno! Tudo bem?

Minha dúvida é como posso anular o footer em algumas views, sendo que em várias views apareça a footer padrão e já em outras views o footer não apareça?

**Comment by Lesnock** [comment]
@majully 
Existe a função $this->view->setTemplate($boolean);
Segundo a documentação:

> "Define se o cabeçalho e rodapé serão inclusos - Padrão: true";

Ou seja, caso você passe `false` para esta função tanto o cabeçalho quando o rodapé não serão inclusos.

**Comment by majully** [comment]
@Lesnock muito obrigado!
Identifiquei a função e já coloquei em uso, ocorreu tudo certo.
