### ISSUE TITLE
Fatal error: Class 'User' not found in C:\wamp\www\sistema\app\controllers\CadastroController.php on line 13

### ISSUE THREAD

**Issue by charlesherbster** [brunosantoshx/hxphp#78]
quando vou cadastrar da esse erro tentei ver o que era mas não encontrei o erro do por que não foi encontrado a class -- Fatal error: Class 'User' not found in C:\wamp\www\sistema\app\controllers\CadastroController.php on line 13

**Comment by charlesherbster** [comment]
quando vou cadastrar da esse erro tentei ver o que era mas não encontrei o erro do por que não foi encontrado a class -- Fatal error: Class 'User' not found in C:\wamp\www\sistema\app\controllers\CadastroController.php on line 13

 ! ) Fatal error: Class 'User' not found in C:\wamp\www\sistema\app\controllers\CadastroController.php on line 13
Call Stack
#	Time	Memory	Function	Location
1	0.0060	138600	{main}( )	...\index.php:0
2	0.4200	1187568	HXPHP\System\App->run( )	...\index.php:36
3	0.4420	1249744	call_user_func_array:{C:\wamp\www\sistema\src\HXPHP\System\App.php:103} ( )	...\App.php:103
4	0.4420	1249936	CadastroController->cadastrarAction( )

**Comment by brunosantoshx** [comment]
Olá @charlesherbster, como vai?

O Model `User` existe e está conforme o ensinado durante a série?
