### ISSUE TITLE
Fatal error: Class 'Form' not found in

### ISSUE THREAD

**Issue by gabiantunes** [brunosantoshx/hxphp#79]
Olá Bruno, tudo bem? Meu sistema está rodando perfeitamente, mas quando efetuo o login e clico em "editar perfil" ele me retorna o erro:

Nenhum menu foi definido para o seguinte nivel de acesso: 
Fatal error: Class 'Form' not found in /home/u602839037/public_html/login/app/views/perfil/editar.phtml on line 12

Poderia me ajudar? Obrigada!

**Comment by gabiantunes** [comment]
Descobri o que era e já resolvi, tinha que atualizar o composer.json com o bootstrap-form!

**Comment by Davidsonc** [comment]
como se faz essa atualização @gabiantunes ?

**Comment by Davidsonc** [comment]
Acabei descobrindo, a solução esta na aula 15 https://youtu.be/komJiCl5S8g?t=80, o vídeo esta no ponto exato. Clique com o botão direito do mouse na pasta do sistema, no menu clique em "git bash here", depois de abrir a janela preta digite "composer require avdbr/php-bootstrap-form:dev-master" , de enter e aguarde a atualização das dependências, quando terminar é só fechar a janela e o erro desaparecerá.
