### ISSUE TITLE
The requested URL /sistema/cadastro was not found on this server.

### ISSUE THREAD

**Issue by SirTroia** [brunosantoshx/hxphp#8]
No video: #3 - MVC + HXPHP + Criando Controllers e Views

Na parte de criar controller Cadastro.
Eu fiz tudo certinho mas quando pesquisei.

localhost/sistema/cadastro

Apareceu:
                  The requested URL /sistema/cadastro was not found on this server.
                  Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 90

**Comment by SirTroia** [comment]
ok... Já resolvi.
Mas agora tenho outro problema.
https://www.youtube.com/watch?v=7zB5tL064zw&index=4&list=PL2NLqGvZxQu2xMnvPKqLz4f9Pljsj-K4B

na parte do video 
![image](https://cloud.githubusercontent.com/assets/16122662/11544028/a8cf8176-9937-11e5-8830-c6e0cdb5096a.png)

fiz tudo certo e deu isto Notice: Undefined index: password in C:\wamp\www\sistema\app\models\User.php on line 14
Call Stack
#	Time	Memory	Function	Location
1	0.0000	250784	{main}( )	..\index.php:0
2	0.0240	1757976	HXPHP\System\App->run( )	..\index.php:28
3	0.0270	1845368	call_user_func_array:{C:\wamp\www\sistema\src\HXPHP\System\App.php:100} ( )	..\App.php:100
4	0.0270	1845704	CadastroController->cadastrarAction( )	..\App.php:100
5	0.0290	1925136	User::cadastrar( )

**Comment by brunosantoshx** [comment]
Olá, como vai?

Você poderia compartilhar com a galera qual foi a solução do problema do primeiro tópico? Esse problema tem sido frequente na série e acho que compartilhar a solução pode ajudar outras pessoas :smiley: 

Quanto a sua dúvida:
O problema deve ser que você colocou outro nome para o field de senha. Verifique o `name="password"`. 

**Obs: Cada dúvida deve ser publicada em uma respectiva issue. Isto ajuda na organização e também possibilitará que outras pessoas com o mesmo problema encontrem facilmente.**

Forte abraço e sucesso sempre!

**Comment by SirTroia** [comment]
Para resolver o 1º problema .

Clique com o lado esquerdo do rato no wamp, depois em Apache , Apache Modules e procure rewrite_module. Clique e de restart ao wamp.
Problema resolvido :D.

**Comment by SirTroia** [comment]
PS: Olá brunosantoshx, gostava de saber se Têm skype de ajuda?.
Tenho tudo certo mas como o meu site é hosteado quando puxo as configs que fiz ao ver  o teu video para  o phpmyadmin do host dá erro.
E gostava que me pudesse ensinar.

**Comment by brunosantoshx** [comment]
@SirTroia, infelizmente não utilizo o Skype com frequência e também não seria capaz de atender à todos de forma alguma kkkk.

Porém, a expectativa deste formato de suporte é que todas as dúvidas sejam solucionadas. 

**Portanto, gostaria que publicasse sua dúvida em uma issue específica no repositório da série e com o máximo de detalhes possíveis, para que eu juntamente com a comunidade, que já está se formando, possamos lhe ajudar.**

Forte abraço e sucesso sempre!
