### ISSUE TITLE
Update dependências

### ISSUE THREAD

**Issue by majully** [brunosantoshx/hxphp#85]
Olá,
Não estou conseguindo atualizar as dependências,
Como faço o update das dependências?

**Comment by skay1994** [comment]
use o comando do `composer update` ou apague a pasta vendor e o arquivo do composer.lock e execute o comando do `composer install` novamente para reinstalar as dependências com as novas versões

**Comment by majully** [comment]
Com esse comando executado o font-awesome não deveria atualizar?
Como faça o update para a nova versão do font-awesome?

**Comment by skay1994** [comment]
não, composer somente atualiza bibliotecas PHP, o fontawesome vc pode gerenciar pelo bower q depende do nodejs

**Comment by brunosantoshx** [comment]
Exatamente como o @skay1994 disse! Bower é para front assim como Composer é para back. 

Forte abraço e sucesso sempre!
