### ISSUE TITLE
problema com a geração do link de redefinição

### ISSUE THREAD

**Issue by thalesreal** [brunosantoshx/hxphp#86]
ola, estou assistindo a 11°aula da serie sistemas de login com niveis de acesso e fiz tudo como foi pedido como eu adaptei para  o meu sistema eu só copiei a pasta src e tals. mas ta dando o seguinte erro: 
" 'O template nao foi localizado: <'TEMPLATES_PATHModules/Messages/password-recovery.json'>' "
ja refiz tudo de novo e to pela segunda vez fazendo passo-a-passo, e ja revi toda a documentação e tals e comparei, e ta tudo certo e queria aprender e tals e não simplesmente pegar ela pronta e adptar. 

pode parecer besta e tals a duvida mas to quase quebrando o note kkk

		$this->load('Modules\Messages', 'password-recovery');
ta dizendo que  o erro ta aqui mas ta tudo certo

**Comment by skay1994** [comment]
você esta com a ultima versão do HXPHP?

**Comment by thalesreal** [comment]
Sim.. com a última release

**Comment by skay1994** [comment]
Dentro do arquivo index.php tem 
```php
define('TEMPLATES_PATH', ROOT_PATH . 'templates' . DS);
```

que define onde é o diretorio q vai buscar os templates, que é na base da aplicacao como na arvore de arquivos do repositorio.

https://github.com/brunosantoshx/hxphp/tree/master/templates

**Comment by thalesreal** [comment]
Por isso que não estou estendendo

**Comment by skay1994** [comment]
copia a pasta `templates` do repositorio e coloca na sua instalacao e ve se resolve

**Comment by thalesreal** [comment]
Mano tem as seguintes instruções no index.php...

Define('DS' , DIRECTORY_SEPARATOR);
DEFINE  ('ROOT_PATH', dirname (__FILE__) . DA);
DEFINE  ('APP__PATH',  'app' . DS);

**Comment by skay1994** [comment]
seu arquivo index.php esta exatamente assim??

```php
	ob_start();
	ini_set('display_errors', 1);
	set_time_limit(0);
	date_default_timezone_set('America/Sao_Paulo');
	setlocale(LC_ALL, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
	define('DS', DIRECTORY_SEPARATOR);
	define('ROOT_PATH', dirname(__FILE__) . DS);
	define('APP_PATH', 'app' . DS);
	define('TEMPLATES_PATH', ROOT_PATH . 'templates' . DS);
	define('HXPHP_VERSION', '2.6.3');
	/**
	 * Verifica se o autoload do Composer está configurado
	 */
	$composer_autoload = 'vendor' . DS . 'autoload.php';
	if ( ! file_exists($composer_autoload))
		die('Execute o comando: composer install');
	if (version_compare(PHP_VERSION, '5.4.0', '<'))
		die('Atualize seu PHP para a vers&atilde;o: 5.4.0 ou superior.');
	require_once($composer_autoload);
	//Start da sessão
	HXPHP\System\Services\StartSession\StartSession::sec_session_start();
	//Inicio da aplicação
	$app = new HXPHP\System\App(require_once APP_PATH . 'config.php');
	$app->ActiveRecord();
	$app->run();
```

**Comment by thalesreal** [comment]
Realmente, agora que vc falou eu olhando o index tá documentação tá
faltando algumas coisas inclusive isso acho q foi o fork da aula 5....
poxa, vou testar aqui! Brigado!!

**Comment by skay1994** [comment]
atualiza seu HXPHP para a ultima versão, durante as aulas foram feitas varias atualizações no sistema, entao pra evitar novos problemas, acho mais facil essa solução

**Comment by thalesreal** [comment]
Beleza Mano, obrigado! Vou seguir sua recomendação

**Comment by skay1994** [comment]
depois fala aki se conseguiu resolver seu problema!

**Comment by thalesreal** [comment]
Blz

**Comment by thalesreal** [comment]
Mano, funcionou cara! Valeu véi!!
