### ISSUE TITLE
Perigoso método de criação de senhas e vulnerabilidade de MITM

### ISSUE THREAD

**Issue by Inkeliz** [brunosantoshx/hxphp#90]
## Criar hashes de senhas:

``` 
$salt = hash('sha512', uniqid(mt_rand(1, mt_getrandmax()), true));
``` 
<sub>https://github.com/brunosantoshx/hxphp/blob/master/src/HXPHP/System/Tools.php#L35-L47</sub>

Segundo a própria documentação do PHP, não deve utilizar o `mt_rand` e o `uniqid` para propósitos criptográficos. Mas do que isto o PHP já possui acesso ao `password_hash()` o que é mais seguro e utiliza o `BCrypt` e na versão PHP 7.3 possivelmente suportará o `Argon2` além do suporte ao Libsodium.

<hr>

## CURL exposto a MITM:

```
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
```

<sub>https://github.com/brunosantoshx/hxphp/blob/eb7986d1ea8066143e02a29263cf1bed392c737b/src/HXPHP/System/Services/SimplecURL/SimplecURL.php#L7-L25</sub>

O PHP possui o `CURLOPT_SSL_VERIFYPEER` que somente no PHP 7.1 ele por padrão é habilitado, *finalmente*. Entretanto, isso indica que todas as versões anteriores ao 7.1 (e que usam o HXPHP) estão vulneráveis à ataques do tipo de [MITM](https://pt.wikipedia.org/wiki/Ataque_man-in-the-middle), como por exemplo DNS Poisoning, Spoofing, Proxy Attacks, ARP Spoofing. Essa mesma informação pode ser obtida na página do CURL.

Não há verificação do certificado, apenas do domínio, o que não é suficiente.

<hr>

Outras vulnerabilidades podem existir.

**Comment by brunosantoshx** [comment]
Olá @Inkeliz, como vai?

Que bom ter o assunto segurança sendo abordado neste repositório. Desde já, quero deixar meu muito obrigado pela sua contribuição.

Sobre seus apontamentos, gostaria de fazer algumas perguntas:

a)  O único propósito para o uso do `uniqid()` e `mt_rand` é gerar uma `random secret key`, isto é, um `salt` que é totalmente aleatório e salvo no banco de dados. A criptografia adotada é `sha-512` ou `SHA-2` e este `salt` é apenas outra camada de segurança para auxiliar usuários que utilizam senhas de fácil dedução, por exemplo. Ainda assim você consideraria isto como uma vulnerabilidade?
b) Sobre o segundo apontamento, esta `option` do `CURL` não exige certificado SSL para efetuar a conexão? 

Fico no aguardo!
Abs

**Comment by Inkeliz** [comment]
Ainda assim você consideraria isto como uma vulnerabilidade?

a) O `uniquid` é baseado em tempo em microssegundos, *isso é não aleatório, é determinado pelo tempo*. O `mt_rand` é um PRNG, assim como `rand` e o `lcg_value`. Utilizar o `openssl_pseudo_random_bytes` também não é um bom caminho a seguir, uma vez que eles são `userspace CSPRNGs` e o ideal é utilizar o direto do Kernel, como o `/dev/urandom`, que tem acesso à entropia diretamente.

O SHA2, desta maneira, não é um bom caminho para senhas, ela é muito rápida, uma GPU descente consegue gerar mais de 100 milhões de hashes em um segundo. Hoje, com 8x AMD R9 290X, você consegue [~800 milhões hashes por segundo](https://hashcat.net/hashcat/). O `salt` não faz a senha ser mais lenta de quebrar, ela apenas faz com que não seja vulnerável a rainbow tables, além disso faz com que o invasor tenha que repetir todas as tentativas do zero, uma vez que *supostamente* cada senha deveria de ter um `salt` diferente.

Inclusive, o PHP possui o [`hash_pbkdf2`](http://php.net/manual/pt_BR/function.hash-pbkdf2.php), que ainda usa o `SHA2` (aka `SHA256`, `SHA384`, `SHA512`) em PBKDF2, que permite assim definir o número de iterações, essa sim faz o hash ser mais lenta. Porém na mesma página mencionam que o `BCrypt` é melhor, e o [`password_hash()`](http://php.net/manual/pt_BR/function.password-hash.php) está disponível desde o PHP 5.5, anos antes que desenvolveu este framework.

O ideal, se for portar a biblioteca para o PHP 7 seria utiliza-la, já com suporte para o Bcrypt e um possível Argon2, [que foi o vencedor da competição](https://password-hashing.net/).

<hr>

b) Não. Ela vai exigir o SSL se o protocolo que possui SSL. O cURL possui vários protocolos, até FTP, STMP, HTTP, HTTPS, FTPS, IMAPS..... Logo, este parâmetro apenas se aplica no HTTPS, FTPS, IMAPS, POP3S, SMTPS, inclusive essa opção no PHP 7.1 é padrão, ou seja todas as requisições são feitas com ela, *e você pode conectar normalmente em sites HTTP*.

Porém no PHP 7.0 (e inferiores) o cURL apenas verifica se o domínio conectado é correspondente ao domínio que está se conectou. Isso é, se conectar com o `facebook.com` ele vai verificar se o certificado é correspondente ao `facebook.com`. 

Utilizando o `CURLOPT_SSL_VERIFYPEER,` ele vai verificar se o emissor do certificado (ou seja, COMODO, GlobalSign, GeoTrust...) foi quem emitiu de fato aquele certificado, você tem que ter a posse de todas as chaves públicas dos emissores (ou aqueles que você confia), [exemplo](https://curl.haxx.se/ca/cacert-2017-01-18.pem), normalmente o próprio sistema operacional possui. 

Se você se conectar em um servidor HTTP (_sem HTTPS_) a conexão **vai ocorrer normalmente**.

A única maneira de impedir a conexão com o HTTP é se utilizar:
```
curl_setopt($ch, CURLOPT_PROTOCOLS , CURLPROTO_HTTPS);
curl_setopt($ch, CURLOPT_REDIR_PROTOCOLS, CURLPROTO_HTTPS);
```

<hr>

Tem vários outros problemas em relação ao  cURL, tipo vários mesmos..

Imagine este cenário:
```
connect($_GET['url']);
```

As vezes a pessoa quer, por exemplo, pegar uma imagem por link, ou fazer um DOM para pegar o Favicon de um website...

Isto expõe dois riscos graves:

1. Não há timeout, *e nem maneira fácil de configurar*, isso indica que você está exposto a DoS por Slow HTTP attack, basicamente, o  cURL por padrão apenas possui `CURLOPT_CONNECTTIMEOUT` definido por padrão (*e mesmo assim é longo*).
2. Não há limite em quais protocolos,  *e nem maneira fácil de configurar*, você está claramente exposto para SSRF, ou seja pode ser inserido `gopher://test.smtp.org:25/_HELO test.org%0AMAIL FROM: %0ARCPT TO: %0ADATA%0ATeste%0A.` ´no parâmetro `url` e assim utilizamos o seu servidor para enviar e-mails.

Várias coisas poderiam ser modificadas, adicionar taxa minima de download/upload, para evitar o problema, definir um timeout, definir quais protocolos, exigir verificação do certificado e inclusive permitir o uso do `CURLOPT_PINNEDPUBLICKEY` para exigir que o certificado seja exatamente o que você tem.

**Comment by carusogabriel** [comment]
Bom dia @Inkeliz 
Sobre esse assunto, você recomenda então o uso da função `password_hash` no método `hashHx` para criptografia de senha/dados?

**Comment by Inkeliz** [comment]
Em resumo sim, o `password_hash` suporta BCrypt que foi feito para essa finalidade.
