### ISSUE TITLE
Qual seria o objetivo do filteredFileName?

### ISSUE THREAD

**Issue by Inkeliz** [brunosantoshx/hxphp#92]
O nome desta função não é auto explicativa, nem mesmo sua função, que apenas remove espaços e remove acentos, coisas que poderia ser feita com o `iconv`, além de não remover múltiplos espaços e enfatizar a remoção de `"`, duas vezes remove o `"`.

Entretanto, isso não remove `../`, `./` o `/`, que pode ser utilizados como falsos nomes para navegar entre diretórios, por exemplo:

```
echo HXPHP\System\Tools::filteredFileName('../../../etc/passwd');
```

Não há qualquer tratamento neste sentido para que possa chamar de "FileName", por mim "FileName" é nome de arquivo, logo o "filtered" seria como filtrar nome de arquivo. Confiar nesta função para este proposito é um erro, além de existir `str_replace()` repetidos, *sinceramente não sei porque existe essa função*.

Deveria de haver duas funções, por exemplo:

- `isFileName(string $string, string $extensao = '') : bool` para verificar se `$string` é um nome de arquivo válido, sem uso de caminhos dinâmicos e com uma extensão fixa ao final, opcional.

- `filterFileName(string $string, string $extensao = '') : string` para tornar uma string qualquer em uma susposto nome de arquivo válido, removendo caminhos dinâmicos e mantendo apenas `aquivo.extensao`, apenas com caracteres ASCII, *sem acentuações*. Dessa forma poderia utilizar tal nome, mesmo que mudanças no nome fossem feitas.

**Comment by carusogabriel** [comment]
Ola @Inkeliz tudo bem?

Quando criei essa função para o framework, foi para facilitar o trabalho com arquivos, visto que os OS tem dificuldades com eles.

**Comment by brunosantoshx** [comment]
Olá @carusogabriel, tudo bem?

Concordo com os apontamentos do @Inkeliz que esta função poderia ser reformulada adotando o uso da função nativa [http://php.net/manual/pt_BR/function.iconv.php](http://php.net/manual/pt_BR/function.iconv.php). O que acha de um PR neste propósito?

Forte abraço e sucesso sempre!

**Comment by carusogabriel** [comment]
Olá @brunosantoshx 

Reformularei esta função para evitar duplicações de códigos.

Abraços!
