### ISSUE TITLE
PHP 7 e Active Records

### ISSUE THREAD

**Issue by skay1994** [brunosantoshx/hxphp#99]
Como o framework do active records nao foi atualizado para o PHP 7, o uso dele pode deixar o sistema com falhas, qual seria a alternativa?

**Comment by carusogabriel** [comment]
Estou usando a versão dev-master do PHPActiveRecord e estou sem problema! Já commitei algumas alterações lá no repositório oficial, de uma olhada

**Comment by skay1994** [comment]
aqui depois de instalar o hx estou recebendo essa mensagem se rodando no PHP 7.1

![image](https://cloud.githubusercontent.com/assets/5720296/24564633/e850270a-1628-11e7-87f9-86ce320ca4c7.png)

**Comment by carusogabriel** [comment]
PHP 7.1 eu ainda não testei, porém, no 7.0.13 está funcionando

**Comment by skay1994** [comment]
o projeto do active records ainda ta sendo atualizado?

**Comment by carusogabriel** [comment]
Sim, olhe os PR no repositório https://github.com/jpfuentes2/php-activerecord e veja as soluções
